package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AccionPersonal generated by hbm2java
 */
@Entity
@Table(name = "ACCION_PERSONAL", schema = "BDTALENTOHUMANO")
public class AccionPersonal implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int acprId;
	private DetallePuesto detallePuesto;
	private TipoAccion tipoAccion;
	private String acprNumeroOficio;
	private String acprResolucion;
	private String acprAutorizacion;
	private Date acprFecha;
	private String acprExplicacion;

	public AccionPersonal() {
	}

	public AccionPersonal(int acprId) {
		this.acprId = acprId;
	}

	public AccionPersonal(int acprId, DetallePuesto detallePuesto, TipoAccion tipoAccion, String acprNumeroOficio,
			String acprResolucion, String acprAutorizacion, Date acprFecha, String acprExplicacion) {
		this.acprId = acprId;
		this.detallePuesto = detallePuesto;
		this.tipoAccion = tipoAccion;
		this.acprNumeroOficio = acprNumeroOficio;
		this.acprResolucion = acprResolucion;
		this.acprAutorizacion = acprAutorizacion;
		this.acprFecha = acprFecha;
		this.acprExplicacion = acprExplicacion;
	}

	@Id

	@Column(name = "ACPR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getAcprId() {
		return this.acprId;
	}

	public void setAcprId(int acprId) {
		this.acprId = acprId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTPS_ID")
	public DetallePuesto getDetallePuesto() {
		return this.detallePuesto;
	}

	public void setDetallePuesto(DetallePuesto detallePuesto) {
		this.detallePuesto = detallePuesto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TPAC_ID")
	public TipoAccion getTipoAccion() {
		return this.tipoAccion;
	}

	public void setTipoAccion(TipoAccion tipoAccion) {
		this.tipoAccion = tipoAccion;
	}

	@Column(name = "ACPR_NUMERO_OFICIO", length = 256)
	public String getAcprNumeroOficio() {
		return this.acprNumeroOficio;
	}

	public void setAcprNumeroOficio(String acprNumeroOficio) {
		this.acprNumeroOficio = acprNumeroOficio;
	}

	@Column(name = "ACPR_RESOLUCION", length = 512)
	public String getAcprResolucion() {
		return this.acprResolucion;
	}

	public void setAcprResolucion(String acprResolucion) {
		this.acprResolucion = acprResolucion;
	}

	@Column(name = "ACPR_AUTORIZACION", length = 512)
	public String getAcprAutorizacion() {
		return this.acprAutorizacion;
	}

	public void setAcprAutorizacion(String acprAutorizacion) {
		this.acprAutorizacion = acprAutorizacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ACPR_FECHA", length = 7)
	public Date getAcprFecha() {
		return this.acprFecha;
	}

	public void setAcprFecha(Date acprFecha) {
		this.acprFecha = acprFecha;
	}

	@Column(name = "ACPR_EXPLICACION", length = 512)
	public String getAcprExplicacion() {
		return this.acprExplicacion;
	}

	public void setAcprExplicacion(String acprExplicacion) {
		this.acprExplicacion = acprExplicacion;
	}

}
