package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AcrDsc generated by hbm2java
 */

@Entity
@Table(name = "ACR_DSC", schema = "BDTALENTOHUMANO")
public class AcrDsc implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int acdsId;
	private Acreedor acreedor;
	private Descuento descuento;
	private int acdsEstado;
	private String acdsObservacion;
	private Set<HistorialDescuento> historialDescuentos = new HashSet<HistorialDescuento>(0);

	public AcrDsc() {
	}

	public AcrDsc(int acdsId) {
		this.acdsId = acdsId;
	}

	public AcrDsc(int acdsId, Acreedor acreedor, Descuento descuento, int acdsEstado, String acdsObservacion,
			Set<HistorialDescuento> historialDescuentos) {
		this.acdsId = acdsId;
		this.acreedor = acreedor;
		this.descuento = descuento;
		this.acdsEstado = acdsEstado;
		this.acdsObservacion = acdsObservacion;
		this.historialDescuentos = historialDescuentos;
	}

	@Id

	@Column(name = "ACDS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getAcdsId() {
		return this.acdsId;
	}

	public void setAcdsId(int acdsId) {
		this.acdsId = acdsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACR_ID")
	public Acreedor getAcreedor() {
		return this.acreedor;
	}

	public void setAcreedor(Acreedor acreedor) {
		this.acreedor = acreedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DSC_ID")
	public Descuento getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Descuento descuento) {
		this.descuento = descuento;
	}

	@Column(name = "ACDS_ESTADO", precision = 22, scale = 0)
	public int getAcdsEstado() {
		return this.acdsEstado;
	}

	public void setAcdsEstado(int acdsEstado) {
		this.acdsEstado = acdsEstado;
	}

	@Column(name = "ACDS_OBSERVACION")
	public String getAcdsObservacion() {
		return this.acdsObservacion;
	}

	public void setAcdsObservacion(String acdsObservacion) {
		this.acdsObservacion = acdsObservacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acrDsc")
	public Set<HistorialDescuento> getHistorialDescuentos() {
		return this.historialDescuentos;
	}

	public void setHistorialDescuentos(Set<HistorialDescuento> historialDescuentos) {
		this.historialDescuentos = historialDescuentos;
	}

}
