package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final


import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Acreedor generated by hbm2java
 */
@Entity
@Table(name = "ACREEDOR", schema = "BDTALENTOHUMANO")
public class Acreedor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int acrId;
	private String acrNombre;
	private String acrRepresentante;
	private String acrIdentificacion;
	private String acrNumeroCuenta;
	private BigDecimal acrTipoCuenta;
	private String acrEmail;
	private BigDecimal acrTipo;
	private Timestamp acrFechaCreacion;
	private Set<AcrDsc> acrDscs = new HashSet<AcrDsc>(0);

	public Acreedor() {
	}

	public Acreedor(int acrId) {
		this.acrId = acrId;
	}

	public Acreedor(int acrId, String acrNombre, String acrRepresentante, String acrIdentificacion,
			String acrNumeroCuenta, BigDecimal acrTipoCuenta, String acrEmail, BigDecimal acrTipo,
			Timestamp  acrFechaCreacion, Set<AcrDsc> acrDscs) {
		this.acrId = acrId;
		this.acrNombre = acrNombre;
		this.acrRepresentante = acrRepresentante;
		this.acrIdentificacion = acrIdentificacion;
		this.acrNumeroCuenta = acrNumeroCuenta;
		this.acrTipoCuenta = acrTipoCuenta;
		this.acrEmail = acrEmail;
		this.acrTipo = acrTipo;
		this.acrFechaCreacion = acrFechaCreacion;
		this.acrDscs = acrDscs;
	}

	@Id

	@Column(name = "ACR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getAcrId() {
		return this.acrId;
	}

	public void setAcrId(int acrId) {
		this.acrId = acrId;
	}

	@Column(name = "ACR_NOMBRE")
	public String getAcrNombre() {
		return this.acrNombre;
	}

	public void setAcrNombre(String acrNombre) {
		this.acrNombre = acrNombre;
	}

	@Column(name = "ACR_REPRESENTANTE")
	public String getAcrRepresentante() {
		return this.acrRepresentante;
	}

	public void setAcrRepresentante(String acrRepresentante) {
		this.acrRepresentante = acrRepresentante;
	}

	@Column(name = "ACR_IDENTIFICACION", length = 13)
	public String getAcrIdentificacion() {
		return this.acrIdentificacion;
	}

	public void setAcrIdentificacion(String acrIdentificacion) {
		this.acrIdentificacion = acrIdentificacion;
	}

	@Column(name = "ACR_NUMERO_CUENTA", length = 13)
	public String getAcrNumeroCuenta() {
		return this.acrNumeroCuenta;
	}

	public void setAcrNumeroCuenta(String acrNumeroCuenta) {
		this.acrNumeroCuenta = acrNumeroCuenta;
	}

	@Column(name = "ACR_TIPO_CUENTA", precision = 22, scale = 0)
	public BigDecimal getAcrTipoCuenta() {
		return this.acrTipoCuenta;
	}

	public void setAcrTipoCuenta(BigDecimal acrTipoCuenta) {
		this.acrTipoCuenta = acrTipoCuenta;
	}

	@Column(name = "ACR_EMAIL")
	public String getAcrEmail() {
		return this.acrEmail;
	}

	public void setAcrEmail(String acrEmail) {
		this.acrEmail = acrEmail;
	}

	@Column(name = "ACR_TIPO", precision = 22, scale = 0)
	public BigDecimal getAcrTipo() {
		return this.acrTipo;
	}

	public void setAcrTipo(BigDecimal acrTipo) {
		this.acrTipo = acrTipo;
	}

	@Column(name = "ACR_FECHA_CREACION")
	public Timestamp getAcrFechaCreacion() {
		return this.acrFechaCreacion;
	}

	public void setAcrFechaCreacion(Timestamp acrFechaCreacion) {
		this.acrFechaCreacion = acrFechaCreacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acreedor")
	public Set<AcrDsc> getAcrDscs() {
		return this.acrDscs;
	}

	public void setAcrDscs(Set<AcrDsc> acrDscs) {
		this.acrDscs = acrDscs;
	}

}
