package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ActividadEsencial generated by hbm2java
 */
@Entity
@Table(name = "ACTIVIDAD_ESENCIAL", schema = "BDTALENTOHUMANO")
public class ActividadEsencial implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int acesId;
	private String acesDescripcion;
	private Set<ActividadPuesto> actividadPuestos = new HashSet<ActividadPuesto>(0);

	public ActividadEsencial() {
	}

	public ActividadEsencial(int acesId) {
		this.acesId = acesId;
	}

	public ActividadEsencial(int acesId, String acesDescripcion, Set<ActividadPuesto> actividadPuestos) {
		this.acesId = acesId;
		this.acesDescripcion = acesDescripcion;
		this.actividadPuestos = actividadPuestos;
	}

	@Id

	@Column(name = "ACES_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getAcesId() {
		return this.acesId;
	}

	public void setAcesId(int acesId) {
		this.acesId = acesId;
	}

	@Column(name = "ACES_DESCRIPCION", length = 512)
	public String getAcesDescripcion() {
		return this.acesDescripcion;
	}

	public void setAcesDescripcion(String acesDescripcion) {
		this.acesDescripcion = acesDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "actividadEsencial")
	public Set<ActividadPuesto> getActividadPuestos() {
		return this.actividadPuestos;
	}

	public void setActividadPuestos(Set<ActividadPuesto> actividadPuestos) {
		this.actividadPuestos = actividadPuestos;
	}

}
