package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ActividadPuesto generated by hbm2java
 */
@Entity
@Table(name = "ACTIVIDAD_PUESTO", schema = "BDTALENTOHUMANO")
public class ActividadPuesto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int acpsId;
	private ActividadEsencial actividadEsencial;
	private Puesto puesto;

	public ActividadPuesto() {
	}

	public ActividadPuesto(int acpsId) {
		this.acpsId = acpsId;
	}

	public ActividadPuesto(int acpsId, ActividadEsencial actividadEsencial, Puesto puesto) {
		this.acpsId = acpsId;
		this.actividadEsencial = actividadEsencial;
		this.puesto = puesto;
	}

	@Id

	@Column(name = "ACPS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getAcpsId() {
		return this.acpsId;
	}

	public void setAcpsId(int acpsId) {
		this.acpsId = acpsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACES_ID")
	public ActividadEsencial getActividadEsencial() {
		return this.actividadEsencial;
	}

	public void setActividadEsencial(ActividadEsencial actividadEsencial) {
		this.actividadEsencial = actividadEsencial;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PST_ID")
	public Puesto getPuesto() {
		return this.puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}

}
