package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AreaConocimiento generated by hbm2java
 */
@Entity
@Table(name = "AREA_CONOCIMIENTO", schema = "BDTALENTOHUMANO")
public class AreaConocimiento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int arcnId;
	private AreaConocimiento areaConocimiento;
	private String arcnDescripcion;
	private String arcnCodigo;
	private BigDecimal arcnJerarquia;
	private Set<PuestoAreaConocimiento> puestoAreaConocimientos = new HashSet<PuestoAreaConocimiento>(0);
	private Set<AreaConocimiento> areaConocimientos = new HashSet<AreaConocimiento>(0);

	public AreaConocimiento() {
	}

	public AreaConocimiento(int arcnId) {
		this.arcnId = arcnId;
	}

	public AreaConocimiento(int arcnId, AreaConocimiento areaConocimiento, String arcnDescripcion, String arcnCodigo,
			BigDecimal arcnJerarquia, Set<PuestoAreaConocimiento> puestoAreaConocimientos,
			Set<AreaConocimiento> areaConocimientos) {
		this.arcnId = arcnId;
		this.areaConocimiento = areaConocimiento;
		this.arcnDescripcion = arcnDescripcion;
		this.arcnCodigo = arcnCodigo;
		this.arcnJerarquia = arcnJerarquia;
		this.puestoAreaConocimientos = puestoAreaConocimientos;
		this.areaConocimientos = areaConocimientos;
	}

	@Id

	@Column(name = "ARCN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getArcnId() {
		return this.arcnId;
	}

	public void setArcnId(int arcnId) {
		this.arcnId = arcnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ARCN_SUB_ID")
	public AreaConocimiento getAreaConocimiento() {
		return this.areaConocimiento;
	}

	public void setAreaConocimiento(AreaConocimiento areaConocimiento) {
		this.areaConocimiento = areaConocimiento;
	}

	@Column(name = "ARCN_DESCRIPCION", length = 128)
	public String getArcnDescripcion() {
		return this.arcnDescripcion;
	}

	public void setArcnDescripcion(String arcnDescripcion) {
		this.arcnDescripcion = arcnDescripcion;
	}

	@Column(name = "ARCN_CODIGO", length = 10)
	public String getArcnCodigo() {
		return this.arcnCodigo;
	}

	public void setArcnCodigo(String arcnCodigo) {
		this.arcnCodigo = arcnCodigo;
	}

	@Column(name = "ARCN_JERARQUIA", precision = 22, scale = 0)
	public BigDecimal getArcnJerarquia() {
		return this.arcnJerarquia;
	}

	public void setArcnJerarquia(BigDecimal arcnJerarquia) {
		this.arcnJerarquia = arcnJerarquia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaConocimiento")
	public Set<PuestoAreaConocimiento> getPuestoAreaConocimientos() {
		return this.puestoAreaConocimientos;
	}

	public void setPuestoAreaConocimientos(Set<PuestoAreaConocimiento> puestoAreaConocimientos) {
		this.puestoAreaConocimientos = puestoAreaConocimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "areaConocimiento")
	public Set<AreaConocimiento> getAreaConocimientos() {
		return this.areaConocimientos;
	}

	public void setAreaConocimientos(Set<AreaConocimiento> areaConocimientos) {
		this.areaConocimientos = areaConocimientos;
	}

}
