package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Candidato generated by hbm2java
 */
@Entity
@Table(name = "CANDIDATO", schema = "BDTALENTOHUMANO")
public class Candidato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int cndId;
	private Tramite tramite;
	private String cndIdentificacion;
	private BigDecimal cndEstado;
	private Set<Contrato> contratos = new HashSet<Contrato>(0);

	public Candidato() {
	}

	public Candidato(int cndId) {
		this.cndId = cndId;
	}

	public Candidato(int cndId, Tramite tramite, String cndIdentificacion, BigDecimal cndEstado,
			Set<Contrato> contratos) {
		this.cndId = cndId;
		this.tramite = tramite;
		this.cndIdentificacion = cndIdentificacion;
		this.cndEstado = cndEstado;
		this.contratos = contratos;
	}

	@Id

	@Column(name = "CND_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCndId() {
		return this.cndId;
	}

	public void setCndId(int cndId) {
		this.cndId = cndId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRM_ID")
	public Tramite getTramite() {
		return this.tramite;
	}

	public void setTramite(Tramite tramite) {
		this.tramite = tramite;
	}

	@Column(name = "CND_IDENTIFICACION", length = 256)
	public String getCndIdentificacion() {
		return this.cndIdentificacion;
	}

	public void setCndIdentificacion(String cndIdentificacion) {
		this.cndIdentificacion = cndIdentificacion;
	}

	@Column(name = "CND_ESTADO", precision = 22, scale = 0)
	public BigDecimal getCndEstado() {
		return this.cndEstado;
	}

	public void setCndEstado(BigDecimal cndEstado) {
		this.cndEstado = cndEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "candidato")
	public Set<Contrato> getContratos() {
		return this.contratos;
	}

	public void setContratos(Set<Contrato> contratos) {
		this.contratos = contratos;
	}

}
