package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoria generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIA", schema = "BDTALENTOHUMANO")
public class Categoria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int ctgId;
	private String ctgDescripcion;
	private String ctgCodigoNomina;
	private BigDecimal ctgEstado;
	private List<CategoriaFalta> categoriaFaltas = new ArrayList<>();
	private List<FichaEmpleado> fichaEmpleados = new ArrayList<>();

	public Categoria() {
	}

	public Categoria(int ctgId) {
		this.ctgId = ctgId;
	}

	public Categoria(int ctgId, String ctgDescripcion, String ctgCodigoNomina, BigDecimal ctgEstado,
			List<CategoriaFalta> categoriaFaltas, List<FichaEmpleado> fichaEmpleados) {
		this.ctgId = ctgId;
		this.ctgDescripcion = ctgDescripcion;
		this.ctgCodigoNomina = ctgCodigoNomina;
		this.ctgEstado = ctgEstado;
		this.categoriaFaltas = categoriaFaltas;
		this.fichaEmpleados = fichaEmpleados;
	}

	@Id

	@Column(name = "CTG_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCtgId() {
		return this.ctgId;
	}

	public void setCtgId(int ctgId) {
		this.ctgId = ctgId;
	}

	@Column(name = "CTG_DESCRIPCION", length = 256)
	public String getCtgDescripcion() {
		return this.ctgDescripcion;
	}

	public void setCtgDescripcion(String ctgDescripcion) {
		this.ctgDescripcion = ctgDescripcion;
	}

	@Column(name = "CTG_CODIGO_NOMINA", length = 2)
	public String getCtgCodigoNomina() {
		return this.ctgCodigoNomina;
	}

	public void setCtgCodigoNomina(String ctgCodigoNomina) {
		this.ctgCodigoNomina = ctgCodigoNomina;
	}

	@Column(name = "CTG_ESTADO", precision = 22, scale = 0)
	public BigDecimal getCtgEstado() {
		return this.ctgEstado;
	}

	public void setCtgEstado(BigDecimal ctgEstado) {
		this.ctgEstado = ctgEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public List<CategoriaFalta> getCategoriaFaltas() {
		return this.categoriaFaltas;
	}

	public void setCategoriaFaltas(List<CategoriaFalta> categoriaFaltas) {
		this.categoriaFaltas = categoriaFaltas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public List<FichaEmpleado> getFichaEmpleados() {
		return this.fichaEmpleados;
	}

	public void setFichaEmpleados(List<FichaEmpleado> fichaEmpleados) {
		this.fichaEmpleados = fichaEmpleados;
	}

}
