package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaFalta generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIA_FALTA", schema = "BDTALENTOHUMANO")
public class CategoriaFalta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int ctgflId;
	private Categoria categoria;
	private Falta falta;
	private int ctgflFrecuenciaMax;
	private int ctgflFrecuenciaMin;
	private int ctgflMinuntosMin;
	private int ctgflMinutosMax;
	private String ctgflObservacion;
	private float ctgflPorcentajeBase;
	private Sancion Sancion;
	private int ctgflEstado;
	private List<DetallePuestoSancion> detallePuestoSancions = new ArrayList<>();
	public CategoriaFalta() {
	}

	public CategoriaFalta(int ctgflId) {
		this.ctgflId = ctgflId;
	}

	public CategoriaFalta(int ctgflId, Categoria categoria, Falta falta, int ctgflFrecuenciaMax,
			int ctgflMinuntosMin, int ctgflMinutosMax, String ctgflObservacion,
			float ctgflPorcentajeBase, int ctgflEstado,
			List<DetallePuestoSancion> detallePuestoSancions) {
		this.ctgflId = ctgflId;
		this.categoria = categoria;
		this.falta = falta;
		this.ctgflFrecuenciaMax = ctgflFrecuenciaMax;
		this.ctgflMinuntosMin = ctgflMinuntosMin;
		this.ctgflMinutosMax = ctgflMinutosMax;
		this.ctgflObservacion = ctgflObservacion;
		this.ctgflPorcentajeBase = ctgflPorcentajeBase;
		this.ctgflEstado = ctgflEstado;
		this.detallePuestoSancions = detallePuestoSancions;
	}

	@Id
	@Column(name = "CTGFL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCtgflId() {
		return this.ctgflId;
	}

	public void setCtgflId(int ctgflId) {
		this.ctgflId = ctgflId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTG_ID")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "FL_ID")
	public Falta getFalta() {
		return this.falta;
	}

	public void setFalta(Falta falta) {
		this.falta = falta;
	}

	@Column(name = "CTGFL_FRECUENCIA_MAX", precision = 22, scale = 0)
	public int  getCtgflFrecuenciaMax() {
		return this.ctgflFrecuenciaMax;
	}

	public void setCtgflFrecuenciaMax(int ctgflFrecuenciaMax) {
		this.ctgflFrecuenciaMax = ctgflFrecuenciaMax;
	}

	@Column(name = "CTGFL_MINUNTOS_MIN", precision = 22, scale = 0)
	public int getCtgflMinuntosMin() {
		return this.ctgflMinuntosMin;
	}

	public void setCtgflMinuntosMin(int ctgflMinuntosMin) {
		this.ctgflMinuntosMin = ctgflMinuntosMin;
	}

	@Column(name = "CTGFL_MINUTOS_MAX", precision = 22, scale = 0)
	public int getCtgflMinutosMax() {
		return this.ctgflMinutosMax;
	}

	public void setCtgflMinutosMax(int ctgflMinutosMax) {
		this.ctgflMinutosMax = ctgflMinutosMax;
	}

	@Column(name = "CTGFL_OBSERVACION", length = 512)
	public String getCtgflObservacion() {
		return this.ctgflObservacion;
	}

	public void setCtgflObservacion(String ctgflObservacion) {
		this.ctgflObservacion = ctgflObservacion;
	}

	@Column(name = "CTGFL_PORCENTAJE__BASE")
	public float getCtgflPorcentajeBase() {
		return this.ctgflPorcentajeBase;
	}

	public void setCtgflPorcentajeBase(float ctgflPorcentajeBase) {
		this.ctgflPorcentajeBase = ctgflPorcentajeBase;
	}


	@Column(name = "CTGFL_ESTADO", precision = 22, scale = 0)
	public int getCtgflEstado() {
		return this.ctgflEstado;
	}

	public void setCtgflEstado(int ctgflEstado) {
		this.ctgflEstado = ctgflEstado;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "categoriaFalta")
	public List<DetallePuestoSancion> getDetallePuestoSancions() {
		return this.detallePuestoSancions;
	}

	public void setDetallePuestoSancions(List<DetallePuestoSancion> detallePuestoSancions) {
		this.detallePuestoSancions = detallePuestoSancions;
	}


	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SN_ID")
	public Sancion getSancion() {
		return Sancion;
	}

	public void setSancion(Sancion Sancion) {
		this.Sancion = Sancion;
	}

	@Column(name = "CTGFL_FRECUENCIA_MIN")
	public int getCtgflFrecuenciaMin() {
		return ctgflFrecuenciaMin;
	}

	public void setCtgflFrecuenciaMin(int ctgflFrecuenciaMin) {
		this.ctgflFrecuenciaMin = ctgflFrecuenciaMin;
	}
	
	

}
