package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaFalta generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIA_FALTA", schema = "BDTALENTOHUMANO")
public class CategoriaFalta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int ctgflId;
	private Categoria categoria;
	private Falta falta;
	private BigDecimal ctgflFrecuenciaMax;
	private BigDecimal ctgflMinuntosMin;
	private BigDecimal ctgflMinutosMax;
	private String ctgflObservacion;
	private BigDecimal ctgflPorcentajeBase;
	private BigDecimal ctgfllPorcentajeVariable;
	private BigDecimal ctgflEstado;
	private Set<DetallePuestoSancion> detallePuestoSancions = new HashSet<DetallePuestoSancion>(0);

	public CategoriaFalta() {
	}

	public CategoriaFalta(int ctgflId) {
		this.ctgflId = ctgflId;
	}

	public CategoriaFalta(int ctgflId, Categoria categoria, Falta falta, BigDecimal ctgflFrecuenciaMax,
			BigDecimal ctgflMinuntosMin, BigDecimal ctgflMinutosMax, String ctgflObservacion,
			BigDecimal ctgflPorcentajeBase, BigDecimal ctgfllPorcentajeVariable, BigDecimal ctgflEstado,
			Set<DetallePuestoSancion> detallePuestoSancions) {
		this.ctgflId = ctgflId;
		this.categoria = categoria;
		this.falta = falta;
		this.ctgflFrecuenciaMax = ctgflFrecuenciaMax;
		this.ctgflMinuntosMin = ctgflMinuntosMin;
		this.ctgflMinutosMax = ctgflMinutosMax;
		this.ctgflObservacion = ctgflObservacion;
		this.ctgflPorcentajeBase = ctgflPorcentajeBase;
		this.ctgfllPorcentajeVariable = ctgfllPorcentajeVariable;
		this.ctgflEstado = ctgflEstado;
		this.detallePuestoSancions = detallePuestoSancions;
	}

	@Id

	@Column(name = "CTGFL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCtgflId() {
		return this.ctgflId;
	}

	public void setCtgflId(int ctgflId) {
		this.ctgflId = ctgflId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTG_ID")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FL_ID")
	public Falta getFalta() {
		return this.falta;
	}

	public void setFalta(Falta falta) {
		this.falta = falta;
	}

	@Column(name = "CTGFL_FRECUENCIA_MAX", precision = 22, scale = 0)
	public BigDecimal getCtgflFrecuenciaMax() {
		return this.ctgflFrecuenciaMax;
	}

	public void setCtgflFrecuenciaMax(BigDecimal ctgflFrecuenciaMax) {
		this.ctgflFrecuenciaMax = ctgflFrecuenciaMax;
	}

	@Column(name = "CTGFL_MINUNTOS_MIN", precision = 22, scale = 0)
	public BigDecimal getCtgflMinuntosMin() {
		return this.ctgflMinuntosMin;
	}

	public void setCtgflMinuntosMin(BigDecimal ctgflMinuntosMin) {
		this.ctgflMinuntosMin = ctgflMinuntosMin;
	}

	@Column(name = "CTGFL_MINUTOS_MAX", precision = 22, scale = 0)
	public BigDecimal getCtgflMinutosMax() {
		return this.ctgflMinutosMax;
	}

	public void setCtgflMinutosMax(BigDecimal ctgflMinutosMax) {
		this.ctgflMinutosMax = ctgflMinutosMax;
	}

	@Column(name = "CTGFL_OBSERVACION", length = 512)
	public String getCtgflObservacion() {
		return this.ctgflObservacion;
	}

	public void setCtgflObservacion(String ctgflObservacion) {
		this.ctgflObservacion = ctgflObservacion;
	}

	@Column(name = "CTGFL_PORCENTAJE__BASE", precision = 22, scale = 0)
	public BigDecimal getCtgflPorcentajeBase() {
		return this.ctgflPorcentajeBase;
	}

	public void setCtgflPorcentajeBase(BigDecimal ctgflPorcentajeBase) {
		this.ctgflPorcentajeBase = ctgflPorcentajeBase;
	}

	@Column(name = "CTGFLL_PORCENTAJE_VARIABLE", precision = 22, scale = 0)
	public BigDecimal getCtgfllPorcentajeVariable() {
		return this.ctgfllPorcentajeVariable;
	}

	public void setCtgfllPorcentajeVariable(BigDecimal ctgfllPorcentajeVariable) {
		this.ctgfllPorcentajeVariable = ctgfllPorcentajeVariable;
	}

	@Column(name = "CTGFL_ESTADO", precision = 22, scale = 0)
	public BigDecimal getCtgflEstado() {
		return this.ctgflEstado;
	}

	public void setCtgflEstado(BigDecimal ctgflEstado) {
		this.ctgflEstado = ctgflEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoriaFalta")
	public Set<DetallePuestoSancion> getDetallePuestoSancions() {
		return this.detallePuestoSancions;
	}

	public void setDetallePuestoSancions(Set<DetallePuestoSancion> detallePuestoSancions) {
		this.detallePuestoSancions = detallePuestoSancions;
	}

}
