package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Competencia generated by hbm2java
 */
@Entity
@Table(name = "COMPETENCIA", schema = "BDTALENTOHUMANO")
public class Competencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int cmpId;
	private String cmpDescripcion;
	private String cmpDefinicion;
	private BigDecimal cmpTipo;
	private Set<NivelCompetencia> nivelCompetencias = new HashSet<NivelCompetencia>(0);

	public Competencia() {
	}

	public Competencia(int cmpId) {
		this.cmpId = cmpId;
	}

	public Competencia(int cmpId, String cmpDescripcion, String cmpDefinicion, BigDecimal cmpTipo,
			Set<NivelCompetencia> nivelCompetencias) {
		this.cmpId = cmpId;
		this.cmpDescripcion = cmpDescripcion;
		this.cmpDefinicion = cmpDefinicion;
		this.cmpTipo = cmpTipo;
		this.nivelCompetencias = nivelCompetencias;
	}

	@Id

	@Column(name = "CMP_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCmpId() {
		return this.cmpId;
	}

	public void setCmpId(int cmpId) {
		this.cmpId = cmpId;
	}

	@Column(name = "CMP_DESCRIPCION", length = 512)
	public String getCmpDescripcion() {
		return this.cmpDescripcion;
	}

	public void setCmpDescripcion(String cmpDescripcion) {
		this.cmpDescripcion = cmpDescripcion;
	}

	@Column(name = "CMP_DEFINICION", length = 512)
	public String getCmpDefinicion() {
		return this.cmpDefinicion;
	}

	public void setCmpDefinicion(String cmpDefinicion) {
		this.cmpDefinicion = cmpDefinicion;
	}

	@Column(name = "CMP_TIPO", precision = 22, scale = 0)
	public BigDecimal getCmpTipo() {
		return this.cmpTipo;
	}

	public void setCmpTipo(BigDecimal cmpTipo) {
		this.cmpTipo = cmpTipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "competencia")
	public Set<NivelCompetencia> getNivelCompetencias() {
		return this.nivelCompetencias;
	}

	public void setNivelCompetencias(Set<NivelCompetencia> nivelCompetencias) {
		this.nivelCompetencias = nivelCompetencias;
	}

}
