package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompetenciaPuesto generated by hbm2java
 */
@Entity
@Table(name = "COMPETENCIA_PUESTO", schema = "BDTALENTOHUMANO")
public class CompetenciaPuesto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int cmpsId;
	private NivelCompetencia nivelCompetencia;
	private Puesto puesto;

	public CompetenciaPuesto() {
	}

	public CompetenciaPuesto(int cmpsId) {
		this.cmpsId = cmpsId;
	}

	public CompetenciaPuesto(int cmpsId, NivelCompetencia nivelCompetencia, Puesto puesto) {
		this.cmpsId = cmpsId;
		this.nivelCompetencia = nivelCompetencia;
		this.puesto = puesto;
	}

	@Id

	@Column(name = "CMPS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCmpsId() {
		return this.cmpsId;
	}

	public void setCmpsId(int cmpsId) {
		this.cmpsId = cmpsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NVCM_ID")
	public NivelCompetencia getNivelCompetencia() {
		return this.nivelCompetencia;
	}

	public void setNivelCompetencia(NivelCompetencia nivelCompetencia) {
		this.nivelCompetencia = nivelCompetencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PST_ID")
	public Puesto getPuesto() {
		return this.puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}

}
