package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Conocimiento generated by hbm2java
 */
@Entity
@Table(name = "CONOCIMIENTO", schema = "BDTALENTOHUMANO")
public class Conocimiento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int cncId;
	private String cncDescripcion;
	private Set<ConocimientoPuesto> conocimientoPuestos = new HashSet<ConocimientoPuesto>(0);

	public Conocimiento() {
	}

	public Conocimiento(int cncId) {
		this.cncId = cncId;
	}

	public Conocimiento(int cncId, String cncDescripcion, Set<ConocimientoPuesto> conocimientoPuestos) {
		this.cncId = cncId;
		this.cncDescripcion = cncDescripcion;
		this.conocimientoPuestos = conocimientoPuestos;
	}

	@Id

	@Column(name = "CNC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCncId() {
		return this.cncId;
	}

	public void setCncId(int cncId) {
		this.cncId = cncId;
	}

	@Column(name = "CNC_DESCRIPCION", length = 512)
	public String getCncDescripcion() {
		return this.cncDescripcion;
	}

	public void setCncDescripcion(String cncDescripcion) {
		this.cncDescripcion = cncDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "conocimiento")
	public Set<ConocimientoPuesto> getConocimientoPuestos() {
		return this.conocimientoPuestos;
	}

	public void setConocimientoPuestos(Set<ConocimientoPuesto> conocimientoPuestos) {
		this.conocimientoPuestos = conocimientoPuestos;
	}

}
