package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ConocimientoPuesto generated by hbm2java
 */
@Entity
@Table(name = "CONOCIMIENTO_PUESTO", schema = "BDTALENTOHUMANO")
public class ConocimientoPuesto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int cnpsId;
	private Conocimiento conocimiento;
	private Puesto puesto;

	public ConocimientoPuesto() {
	}

	public ConocimientoPuesto(int cnpsId) {
		this.cnpsId = cnpsId;
	}

	public ConocimientoPuesto(int cnpsId, Conocimiento conocimiento, Puesto puesto) {
		this.cnpsId = cnpsId;
		this.conocimiento = conocimiento;
		this.puesto = puesto;
	}

	@Id

	@Column(name = "CNPS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCnpsId() {
		return this.cnpsId;
	}

	public void setCnpsId(int cnpsId) {
		this.cnpsId = cnpsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CNC_ID")
	public Conocimiento getConocimiento() {
		return this.conocimiento;
	}

	public void setConocimiento(Conocimiento conocimiento) {
		this.conocimiento = conocimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PST_ID")
	public Puesto getPuesto() {
		return this.puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}

}
