package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contrato generated by hbm2java
 */
@Entity
@Table(name = "CONTRATO", schema = "BDTALENTOHUMANO")
public class Contrato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int cntId;
	private Candidato candidato;
	private TipoContrato tipoContrato;
	private Date cntFechaInicio;
	private Date cntFechaFin;
	private BigDecimal cntEstado;
	private Set<DetallePuesto> detallePuestos = new HashSet<DetallePuesto>(0);

	public Contrato() {
	}

	public Contrato(int cntId) {
		this.cntId = cntId;
	}

	public Contrato(int cntId, Candidato candidato, TipoContrato tipoContrato, Date cntFechaInicio, Date cntFechaFin,
			BigDecimal cntEstado, Set<DetallePuesto> detallePuestos) {
		this.cntId = cntId;
		this.candidato = candidato;
		this.tipoContrato = tipoContrato;
		this.cntFechaInicio = cntFechaInicio;
		this.cntFechaFin = cntFechaFin;
		this.cntEstado = cntEstado;
		this.detallePuestos = detallePuestos;
	}

	@Id

	@Column(name = "CNT_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCntId() {
		return this.cntId;
	}

	public void setCntId(int cntId) {
		this.cntId = cntId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CND_ID")
	public Candidato getCandidato() {
		return this.candidato;
	}

	public void setCandidato(Candidato candidato) {
		this.candidato = candidato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TPCN_ID")
	public TipoContrato getTipoContrato() {
		return this.tipoContrato;
	}

	public void setTipoContrato(TipoContrato tipoContrato) {
		this.tipoContrato = tipoContrato;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CNT_FECHA_INICIO", length = 7)
	public Date getCntFechaInicio() {
		return this.cntFechaInicio;
	}

	public void setCntFechaInicio(Date cntFechaInicio) {
		this.cntFechaInicio = cntFechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CNT_FECHA_FIN", length = 7)
	public Date getCntFechaFin() {
		return this.cntFechaFin;
	}

	public void setCntFechaFin(Date cntFechaFin) {
		this.cntFechaFin = cntFechaFin;
	}

	@Column(name = "CNT_ESTADO", precision = 22, scale = 0)
	public BigDecimal getCntEstado() {
		return this.cntEstado;
	}

	public void setCntEstado(BigDecimal cntEstado) {
		this.cntEstado = cntEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contrato")
	public Set<DetallePuesto> getDetallePuestos() {
		return this.detallePuestos;
	}

	public void setDetallePuestos(Set<DetallePuesto> detallePuestos) {
		this.detallePuestos = detallePuestos;
	}

	@Override
	public String toString() {
		return "Contrato [cntId=" + cntId + ", candidato=" + candidato + ", tipoContrato=" + tipoContrato
				+ ", cntFechaInicio=" + cntFechaInicio + ", cntFechaFin=" + cntFechaFin + ", cntEstado=" + cntEstado
				+ ", detallePuestos=" + detallePuestos + "]";
	}

}
