package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ControlPago generated by hbm2java
 */
@Entity
@Table(name = "CONTROL_PAGO", schema = "BDTALENTOHUMANO")
public class ControlPago implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int cntPagId;
	private Usuario usuario;
	private Serializable cntPagFecha;
	private BigDecimal cntPagTransaccion;
	private BigDecimal cntPagMes;
	private BigDecimal cntPagAnio;
	private Set<RolPago> rolPagos = new HashSet<RolPago>(0);

	public ControlPago() {
	}

	public ControlPago(int cntPagId) {
		this.cntPagId = cntPagId;
	}

	public ControlPago(int cntPagId, Usuario usuario, Serializable cntPagFecha, BigDecimal cntPagTransaccion,
			BigDecimal cntPagMes, BigDecimal cntPagAnio, Set<RolPago> rolPagos) {
		this.cntPagId = cntPagId;
		this.usuario = usuario;
		this.cntPagFecha = cntPagFecha;
		this.cntPagTransaccion = cntPagTransaccion;
		this.cntPagMes = cntPagMes;
		this.cntPagAnio = cntPagAnio;
		this.rolPagos = rolPagos;
	}

	@Id

	@Column(name = "CNT_PAG_ID_", unique = true, nullable = false, precision = 6, scale = 0)
	public int getCntPagId() {
		return this.cntPagId;
	}

	public void setCntPagId(int cntPagId) {
		this.cntPagId = cntPagId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "CNT_PAG_FECHA")
	public Serializable getCntPagFecha() {
		return this.cntPagFecha;
	}

	public void setCntPagFecha(Serializable cntPagFecha) {
		this.cntPagFecha = cntPagFecha;
	}

	@Column(name = "CNT_PAG_TRANSACCION", precision = 22, scale = 0)
	public BigDecimal getCntPagTransaccion() {
		return this.cntPagTransaccion;
	}

	public void setCntPagTransaccion(BigDecimal cntPagTransaccion) {
		this.cntPagTransaccion = cntPagTransaccion;
	}

	@Column(name = "CNT_PAG_MES", precision = 22, scale = 0)
	public BigDecimal getCntPagMes() {
		return this.cntPagMes;
	}

	public void setCntPagMes(BigDecimal cntPagMes) {
		this.cntPagMes = cntPagMes;
	}

	@Column(name = "CNT_PAG_ANIO", precision = 22, scale = 0)
	public BigDecimal getCntPagAnio() {
		return this.cntPagAnio;
	}

	public void setCntPagAnio(BigDecimal cntPagAnio) {
		this.cntPagAnio = cntPagAnio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "controlPago")
	public Set<RolPago> getRolPagos() {
		return this.rolPagos;
	}

	public void setRolPagos(Set<RolPago> rolPagos) {
		this.rolPagos = rolPagos;
	}

}
