package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DemoOrderItems generated by hbm2java
 */
@Entity
@Table(name = "DEMO_ORDER_ITEMS", schema = "BDTALENTOHUMANO")
public class DemoOrderItems implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short orderItemId;
	private DemoOrders demoOrders;
	private DemoProductInfo demoProductInfo;
	private BigDecimal unitPrice;
	private int quantity;

	public DemoOrderItems() {
	}

	public DemoOrderItems(short orderItemId, DemoOrders demoOrders, DemoProductInfo demoProductInfo,
			BigDecimal unitPrice, int quantity) {
		this.orderItemId = orderItemId;
		this.demoOrders = demoOrders;
		this.demoProductInfo = demoProductInfo;
		this.unitPrice = unitPrice;
		this.quantity = quantity;
	}

	@Id

	@Column(name = "ORDER_ITEM_ID", unique = true, nullable = false, precision = 3, scale = 0)
	public short getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(short orderItemId) {
		this.orderItemId = orderItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ORDER_ID", nullable = false)
	public DemoOrders getDemoOrders() {
		return this.demoOrders;
	}

	public void setDemoOrders(DemoOrders demoOrders) {
		this.demoOrders = demoOrders;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRODUCT_ID", nullable = false)
	public DemoProductInfo getDemoProductInfo() {
		return this.demoProductInfo;
	}

	public void setDemoProductInfo(DemoProductInfo demoProductInfo) {
		this.demoProductInfo = demoProductInfo;
	}

	@Column(name = "UNIT_PRICE", nullable = false, precision = 8)
	public BigDecimal getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(BigDecimal unitPrice) {
		this.unitPrice = unitPrice;
	}

	@Column(name = "QUANTITY", nullable = false, precision = 8, scale = 0)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
