package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dependencia generated by hbm2java
 */
@Entity
@Table(name = "DEPENDENCIA", schema = "BDTALENTOHUMANO")
public class Dependencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int dpnId;
	private Dependencia dependencia;
	private String dpnDescripcion;
	private BigDecimal dpnTipo;
	private Set<Dependencia> dependencias = new HashSet<Dependencia>(0);
	private Set<DetallePuesto> detallePuestos = new HashSet<DetallePuesto>(0);

	public Dependencia() {
	}

	public Dependencia(int dpnId) {
		this.dpnId = dpnId;
	}

	public Dependencia(int dpnId, Dependencia dependencia, String dpnDescripcion, BigDecimal dpnTipo,
			Set<Dependencia> dependencias, Set<DetallePuesto> detallePuestos) {
		this.dpnId = dpnId;
		this.dependencia = dependencia;
		this.dpnDescripcion = dpnDescripcion;
		this.dpnTipo = dpnTipo;
		this.dependencias = dependencias;
		this.detallePuestos = detallePuestos;
	}

	@Id

	@Column(name = "DPN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getDpnId() {
		return this.dpnId;
	}

	public void setDpnId(int dpnId) {
		this.dpnId = dpnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DEP_DPN_ID")
	public Dependencia getDependencia() {
		return this.dependencia;
	}

	public void setDependencia(Dependencia dependencia) {
		this.dependencia = dependencia;
	}

	@Column(name = "DPN_DESCRIPCION", length = 512)
	public String getDpnDescripcion() {
		return this.dpnDescripcion;
	}

	public void setDpnDescripcion(String dpnDescripcion) {
		this.dpnDescripcion = dpnDescripcion;
	}

	@Column(name = "DPN_TIPO", precision = 22, scale = 0)
	public BigDecimal getDpnTipo() {
		return this.dpnTipo;
	}

	public void setDpnTipo(BigDecimal dpnTipo) {
		this.dpnTipo = dpnTipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dependencia")
	public Set<Dependencia> getDependencias() {
		return this.dependencias;
	}

	public void setDependencias(Set<Dependencia> dependencias) {
		this.dependencias = dependencias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dependencia")
	public Set<DetallePuesto> getDetallePuestos() {
		return this.detallePuestos;
	}

	public void setDetallePuestos(Set<DetallePuesto> detallePuestos) {
		this.detallePuestos = detallePuestos;
	}

}
