package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Descuento generated by hbm2java
 */
@Entity
@Table(name = "DESCUENTO", schema = "BDTALENTOHUMANO")
public class Descuento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int dscId;
	private String dscDescripcion;
	private BigDecimal dscCategoria;
	private BigDecimal dscMonto;
	private BigDecimal dscPorcentaje;
	private Character  dscCodigoInternoNomina;
	private BigDecimal dscPrioridad;
	private BigDecimal dscVigenciaPeriodo;
	private Date dscTmpFechaInicio;
	private Date dscTmpFechaFin;
	private BigDecimal dscEstado;
	private Set<AcrDsc> acrDscs = new HashSet<AcrDsc>(0);

	public Descuento() {
	}

	public Descuento(int dscId) {
		this.dscId = dscId;
	}

	public Descuento(int dscId, String dscDescripcion, BigDecimal dscCategoria, BigDecimal dscMonto,
			BigDecimal dscPorcentaje, Character dscCodigoInternoNomina, BigDecimal dscPrioridad,
			BigDecimal dscVigenciaPeriodo, Date dscTmpFechaInicio, Date dscTmpFechaFin, BigDecimal dscEstado,
			Set<AcrDsc> acrDscs) {
		this.dscId = dscId;
		this.dscDescripcion = dscDescripcion;
		this.dscCategoria = dscCategoria;
		this.dscMonto = dscMonto;
		this.dscPorcentaje = dscPorcentaje;
		this.dscCodigoInternoNomina = dscCodigoInternoNomina;
		this.dscPrioridad = dscPrioridad;
		this.dscVigenciaPeriodo = dscVigenciaPeriodo;
		this.dscTmpFechaInicio = dscTmpFechaInicio;
		this.dscTmpFechaFin = dscTmpFechaFin;
		this.dscEstado = dscEstado;
		this.acrDscs = acrDscs;
	}

	@Id

	@Column(name = "DSC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getDscId() {
		return this.dscId;
	}

	public void setDscId(int dscId) {
		this.dscId = dscId;
	}

	@Column(name = "DSC_DESCRIPCION")
	public String getDscDescripcion() {
		return this.dscDescripcion;
	}

	public void setDscDescripcion(String dscDescripcion) {
		this.dscDescripcion = dscDescripcion;
	}

	@Column(name = "DSC_CATEGORIA", precision = 22, scale = 0)
	public BigDecimal getDscCategoria() {
		return this.dscCategoria;
	}

	public void setDscCategoria(BigDecimal dscCategoria) {
		this.dscCategoria = dscCategoria;
	}

	@Column(name = "DSC_MONTO", precision = 4)
	public BigDecimal getDscMonto() {
		return this.dscMonto;
	}

	public void setDscMonto(BigDecimal dscMonto) {
		this.dscMonto = dscMonto;
	}

	@Column(name = "DSC_PORCENTAJE", precision = 4)
	public BigDecimal getDscPorcentaje() {
		return this.dscPorcentaje;
	}

	public void setDscPorcentaje(BigDecimal dscPorcentaje) {
		this.dscPorcentaje = dscPorcentaje;
	}

	@Column(name = "DSC_CODIGO_INTERNO_NOMINA", length = 3)
	public Character getDscCodigoInternoNomina() {
		return this.dscCodigoInternoNomina;
	}

	public void setDscCodigoInternoNomina(Character dscCodigoInternoNomina) {
		this.dscCodigoInternoNomina = dscCodigoInternoNomina;
	}

	@Column(name = "DSC_PRIORIDAD", precision = 22, scale = 0)
	public BigDecimal getDscPrioridad() {
		return this.dscPrioridad;
	}

	public void setDscPrioridad(BigDecimal dscPrioridad) {
		this.dscPrioridad = dscPrioridad;
	}

	@Column(name = "DSC_VIGENCIA_PERIODO", precision = 22, scale = 0)
	public BigDecimal getDscVigenciaPeriodo() {
		return this.dscVigenciaPeriodo;
	}

	public void setDscVigenciaPeriodo(BigDecimal dscVigenciaPeriodo) {
		this.dscVigenciaPeriodo = dscVigenciaPeriodo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DSC_TMP_FECHA_INICIO", length = 7)
	public Date getDscTmpFechaInicio() {
		return this.dscTmpFechaInicio;
	}

	public void setDscTmpFechaInicio(Date dscTmpFechaInicio) {
		this.dscTmpFechaInicio = dscTmpFechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DSC_TMP_FECHA_FIN", length = 7)
	public Date getDscTmpFechaFin() {
		return this.dscTmpFechaFin;
	}

	public void setDscTmpFechaFin(Date dscTmpFechaFin) {
		this.dscTmpFechaFin = dscTmpFechaFin;
	}

	@Column(name = "DSC_ESTADO", precision = 22, scale = 0)
	public BigDecimal getDscEstado() {
		return this.dscEstado;
	}

	public void setDscEstado(BigDecimal dscEstado) {
		this.dscEstado = dscEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "descuento")
	public Set<AcrDsc> getAcrDscs() {
		return this.acrDscs;
	}

	public void setAcrDscs(Set<AcrDsc> acrDscs) {
		this.acrDscs = acrDscs;
	}

}
