package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Destreza generated by hbm2java
 */
@Entity
@Table(name = "DESTREZA", schema = "BDTALENTOHUMANO")
public class Destreza implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int dstId;
	private String dstDescripcion;
	private Set<DestrezaPuesto> destrezaPuestos = new HashSet<DestrezaPuesto>(0);

	public Destreza() {
	}

	public Destreza(int dstId) {
		this.dstId = dstId;
	}

	public Destreza(int dstId, String dstDescripcion, Set<DestrezaPuesto> destrezaPuestos) {
		this.dstId = dstId;
		this.dstDescripcion = dstDescripcion;
		this.destrezaPuestos = destrezaPuestos;
	}

	@Id

	@Column(name = "DST_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getDstId() {
		return this.dstId;
	}

	public void setDstId(int dstId) {
		this.dstId = dstId;
	}

	@Column(name = "DST_DESCRIPCION", length = 512)
	public String getDstDescripcion() {
		return this.dstDescripcion;
	}

	public void setDstDescripcion(String dstDescripcion) {
		this.dstDescripcion = dstDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "destreza")
	public Set<DestrezaPuesto> getDestrezaPuestos() {
		return this.destrezaPuestos;
	}

	public void setDestrezaPuestos(Set<DestrezaPuesto> destrezaPuestos) {
		this.destrezaPuestos = destrezaPuestos;
	}

}
