package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DestrezaPuesto generated by hbm2java
 */
@Entity
@Table(name = "DESTREZA_PUESTO", schema = "BDTALENTOHUMANO")
public class DestrezaPuesto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int dspsId;
	private Destreza destreza;
	private Puesto puesto;

	public DestrezaPuesto() {
	}

	public DestrezaPuesto(int dspsId) {
		this.dspsId = dspsId;
	}

	public DestrezaPuesto(int dspsId, Destreza destreza, Puesto puesto) {
		this.dspsId = dspsId;
		this.destreza = destreza;
		this.puesto = puesto;
	}

	@Id

	@Column(name = "DSPS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getDspsId() {
		return this.dspsId;
	}

	public void setDspsId(int dspsId) {
		this.dspsId = dspsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DST_ID")
	public Destreza getDestreza() {
		return this.destreza;
	}

	public void setDestreza(Destreza destreza) {
		this.destreza = destreza;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PST_ID")
	public Puesto getPuesto() {
		return this.puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}

}
