package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DetallePuesto generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_PUESTO", schema = "BDTALENTOHUMANO")
public class DetallePuesto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int dtpsId;
	private Contrato contrato;
	private Dependencia dependencia;
	private FichaEmpleado fichaEmpleado;
	private Puesto puesto;
	private RelacionLaboral relacionLaboral;
	private BigDecimal dtpsEstado;
	private Set<Distributivo> distributivos = new HashSet<Distributivo>(0);
	private Set<AccionPersonal> accionPersonals = new HashSet<AccionPersonal>(0);
	private Set<Vacacion> vacacions = new HashSet<Vacacion>(0);
	private Set<DetallePuestoSancion> detallePuestoSancions = new HashSet<DetallePuestoSancion>(0);
	private Set<LicenciaYPermiso> licenciaYPermisos = new HashSet<LicenciaYPermiso>(0);
	private Set<SaldoVacacion> saldoVacacions = new HashSet<SaldoVacacion>(0);

	public DetallePuesto() {
	}

	public DetallePuesto(int dtpsId) {
		this.dtpsId = dtpsId;
	}

	public DetallePuesto(int dtpsId, Contrato contrato, Dependencia dependencia, FichaEmpleado fichaEmpleado,
			Puesto puesto, RelacionLaboral relacionLaboral, BigDecimal dtpsEstado, Set<Distributivo> distributivos,
			Set<AccionPersonal> accionPersonals, Set<Vacacion> vacacions,
			Set<DetallePuestoSancion> detallePuestoSancions, Set<LicenciaYPermiso> licenciaYPermisos,
			Set<SaldoVacacion> saldoVacacions) {
		this.dtpsId = dtpsId;
		this.contrato = contrato;
		this.dependencia = dependencia;
		this.fichaEmpleado = fichaEmpleado;
		this.puesto = puesto;
		this.relacionLaboral = relacionLaboral;
		this.dtpsEstado = dtpsEstado;
		this.distributivos = distributivos;
		this.accionPersonals = accionPersonals;
		this.vacacions = vacacions;
		this.detallePuestoSancions = detallePuestoSancions;
		this.licenciaYPermisos = licenciaYPermisos;
		this.saldoVacacions = saldoVacacions;
	}

	@Id

	@Column(name = "DTPS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getDtpsId() {
		return this.dtpsId;
	}

	public void setDtpsId(int dtpsId) {
		this.dtpsId = dtpsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CNT_ID")
	public Contrato getContrato() {
		return this.contrato;
	}

	public void setContrato(Contrato contrato) {
		this.contrato = contrato;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DPN_ID")
	public Dependencia getDependencia() {
		return this.dependencia;
	}

	public void setDependencia(Dependencia dependencia) {
		this.dependencia = dependencia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FCEM_ID")
	public FichaEmpleado getFichaEmpleado() {
		return this.fichaEmpleado;
	}

	public void setFichaEmpleado(FichaEmpleado fichaEmpleado) {
		this.fichaEmpleado = fichaEmpleado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PST_ID")
	public Puesto getPuesto() {
		return this.puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "RLLB_ID")
	public RelacionLaboral getRelacionLaboral() {
		return this.relacionLaboral;
	}

	public void setRelacionLaboral(RelacionLaboral relacionLaboral) {
		this.relacionLaboral = relacionLaboral;
	}

	@Column(name = "DTPS_ESTADO", precision = 22, scale = 0)
	public BigDecimal getDtpsEstado() {
		return this.dtpsEstado;
	}

	public void setDtpsEstado(BigDecimal dtpsEstado) {
		this.dtpsEstado = dtpsEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detallePuesto")
	public Set<Distributivo> getDistributivos() {
		return this.distributivos;
	}

	public void setDistributivos(Set<Distributivo> distributivos) {
		this.distributivos = distributivos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detallePuesto")
	public Set<AccionPersonal> getAccionPersonals() {
		return this.accionPersonals;
	}

	public void setAccionPersonals(Set<AccionPersonal> accionPersonals) {
		this.accionPersonals = accionPersonals;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detallePuesto")
	public Set<Vacacion> getVacacions() {
		return this.vacacions;
	}

	public void setVacacions(Set<Vacacion> vacacions) {
		this.vacacions = vacacions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detallePuesto")
	public Set<DetallePuestoSancion> getDetallePuestoSancions() {
		return this.detallePuestoSancions;
	}

	public void setDetallePuestoSancions(Set<DetallePuestoSancion> detallePuestoSancions) {
		this.detallePuestoSancions = detallePuestoSancions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detallePuesto")
	public Set<LicenciaYPermiso> getLicenciaYPermisos() {
		return this.licenciaYPermisos;
	}

	public void setLicenciaYPermisos(Set<LicenciaYPermiso> licenciaYPermisos) {
		this.licenciaYPermisos = licenciaYPermisos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "detallePuesto")
	public Set<SaldoVacacion> getSaldoVacacions() {
		return this.saldoVacacions;
	}

	public void setSaldoVacacions(Set<SaldoVacacion> saldoVacacions) {
		this.saldoVacacions = saldoVacacions;
	}

}
