package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Time;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DetallePuestoSancion generated by hbm2java
 */
@Entity
@Table(name = "DETALLE_PUESTO_SANCION", schema = "BDTALENTOHUMANO")
public class DetallePuestoSancion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int dtpssnId;
	private CategoriaFalta categoriaFalta;
	private DetallePuesto detallePuesto;
	private Sancion sancion;
	private Timestamp dtpssnFechaEmision;
	private BigDecimal dtpssnMes;
	private BigDecimal dtpssnAno;
	private BigDecimal dtpssnDias;
	private BigDecimal dtpssnFrecuencia;
	private BigDecimal dtpssnNumaccion;
	private String dtpssnObservacion;
	private BigDecimal dtpssnValor;
	private String dtpssnMotivoInsub;
	private BigDecimal dtpssnEstado;
	private BigDecimal dtpssnMinutos;

	public DetallePuestoSancion() {
	}

	public DetallePuestoSancion(int dtpssnId) {
		this.dtpssnId = dtpssnId;
	}

	public DetallePuestoSancion(int dtpssnId, CategoriaFalta categoriaFalta, DetallePuesto detallePuesto,
			Sancion sancion, Timestamp dtpssnFechaEmision, BigDecimal dtpssnMes, BigDecimal dtpssnAno,
			BigDecimal dtpssnDias, BigDecimal dtpssnFrecuencia, BigDecimal dtpssnNumaccion, String dtpssnObservacion,
			BigDecimal dtpssnValor, String dtpssnMotivoInsub, BigDecimal dtpssnEstado, BigDecimal dtpssnMinutos) {
		this.dtpssnId = dtpssnId;
		this.categoriaFalta = categoriaFalta;
		this.detallePuesto = detallePuesto;
		this.sancion = sancion;
		this.dtpssnFechaEmision = dtpssnFechaEmision;
		this.dtpssnMes = dtpssnMes;
		this.dtpssnAno = dtpssnAno;
		this.dtpssnDias = dtpssnDias;
		this.dtpssnFrecuencia = dtpssnFrecuencia;
		this.dtpssnNumaccion = dtpssnNumaccion;
		this.dtpssnObservacion = dtpssnObservacion;
		this.dtpssnValor = dtpssnValor;
		this.dtpssnMotivoInsub = dtpssnMotivoInsub;
		this.dtpssnEstado = dtpssnEstado;
		this.dtpssnMinutos = dtpssnMinutos;
	}

	@Id

	@Column(name = "DTPSSN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getDtpssnId() {
		return this.dtpssnId;
	}

	public void setDtpssnId(int dtpssnId) {
		this.dtpssnId = dtpssnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CTGFL_ID")
	public CategoriaFalta getCategoriaFalta() {
		return this.categoriaFalta;
	}

	public void setCategoriaFalta(CategoriaFalta categoriaFalta) {
		this.categoriaFalta = categoriaFalta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTPS_ID")
	public DetallePuesto getDetallePuesto() {
		return this.detallePuesto;
	}

	public void setDetallePuesto(DetallePuesto detallePuesto) {
		this.detallePuesto = detallePuesto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SN_ID")
	public Sancion getSancion() {
		return this.sancion;
	}

	public void setSancion(Sancion sancion) {
		this.sancion = sancion;
	}

	@Column(name = "DTPSSN_FECHA_EMISION")
	public Timestamp  getDtpssnFechaEmision() {
		return this.dtpssnFechaEmision;
	}

	public void setDtpssnFechaEmision(Timestamp dtpssnFechaEmision) {
		this.dtpssnFechaEmision = dtpssnFechaEmision;
	}

	@Column(name = "DTPSSN_MES", precision = 22, scale = 0)
	public BigDecimal getDtpssnMes() {
		return this.dtpssnMes;
	}

	public void setDtpssnMes(BigDecimal dtpssnMes) {
		this.dtpssnMes = dtpssnMes;
	}

	@Column(name = "DTPSSN_ANO", precision = 22, scale = 0)
	public BigDecimal getDtpssnAno() {
		return this.dtpssnAno;
	}

	public void setDtpssnAno(BigDecimal dtpssnAno) {
		this.dtpssnAno = dtpssnAno;
	}

	@Column(name = "DTPSSN_DIAS", precision = 22, scale = 0)
	public BigDecimal getDtpssnDias() {
		return this.dtpssnDias;
	}

	public void setDtpssnDias(BigDecimal dtpssnDias) {
		this.dtpssnDias = dtpssnDias;
	}

	@Column(name = "DTPSSN_FRECUENCIA", precision = 22, scale = 0)
	public BigDecimal getDtpssnFrecuencia() {
		return this.dtpssnFrecuencia;
	}

	public void setDtpssnFrecuencia(BigDecimal dtpssnFrecuencia) {
		this.dtpssnFrecuencia = dtpssnFrecuencia;
	}

	@Column(name = "DTPSSN_NUMACCION", precision = 22, scale = 0)
	public BigDecimal getDtpssnNumaccion() {
		return this.dtpssnNumaccion;
	}

	public void setDtpssnNumaccion(BigDecimal dtpssnNumaccion) {
		this.dtpssnNumaccion = dtpssnNumaccion;
	}

	@Column(name = "DTPSSN_OBSERVACION", length = 512)
	public String getDtpssnObservacion() {
		return this.dtpssnObservacion;
	}

	public void setDtpssnObservacion(String dtpssnObservacion) {
		this.dtpssnObservacion = dtpssnObservacion;
	}

	@Column(name = "DTPSSN_VALOR", precision = 22, scale = 0)
	public BigDecimal getDtpssnValor() {
		return this.dtpssnValor;
	}

	public void setDtpssnValor(BigDecimal dtpssnValor) {
		this.dtpssnValor = dtpssnValor;
	}

	@Column(name = "DTPSSN_MOTIVO_INSUB", length = 512)
	public String getDtpssnMotivoInsub() {
		return this.dtpssnMotivoInsub;
	}

	public void setDtpssnMotivoInsub(String dtpssnMotivoInsub) {
		this.dtpssnMotivoInsub = dtpssnMotivoInsub;
	}

	@Column(name = "DTPSSN_ESTADO", precision = 22, scale = 0)
	public BigDecimal getDtpssnEstado() {
		return this.dtpssnEstado;
	}

	public void setDtpssnEstado(BigDecimal dtpssnEstado) {
		this.dtpssnEstado = dtpssnEstado;
	}

	@Column(name = "DTPSSN_MINUTOS", precision = 22, scale = 0)
	public BigDecimal getDtpssnMinutos() {
		return this.dtpssnMinutos;
	}

	public void setDtpssnMinutos(BigDecimal dtpssnMinutos) {
		this.dtpssnMinutos = dtpssnMinutos;
	}

}
