package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Distributivo generated by hbm2java
 */
@Entity
@Table(name = "DISTRIBUTIVO", schema = "BDTALENTOHUMANO")
public class Distributivo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int dstId;
	private DetallePuesto detallePuesto;
	private Partida partida;
	private BigDecimal dstEstado;

	public Distributivo() {
	}

	public Distributivo(int dstId) {
		this.dstId = dstId;
	}

	public Distributivo(int dstId, DetallePuesto detallePuesto, Partida partida, BigDecimal dstEstado) {
		this.dstId = dstId;
		this.detallePuesto = detallePuesto;
		this.partida = partida;
		this.dstEstado = dstEstado;
	}

	@Id

	@Column(name = "DST_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getDstId() {
		return this.dstId;
	}

	public void setDstId(int dstId) {
		this.dstId = dstId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTPS_ID")
	public DetallePuesto getDetallePuesto() {
		return this.detallePuesto;
	}

	public void setDetallePuesto(DetallePuesto detallePuesto) {
		this.detallePuesto = detallePuesto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRT_ID")
	public Partida getPartida() {
		return this.partida;
	}

	public void setPartida(Partida partida) {
		this.partida = partida;
	}

	@Column(name = "DST_ESTADO", precision = 22, scale = 0)
	public BigDecimal getDstEstado() {
		return this.dstEstado;
	}

	public void setDstEstado(BigDecimal dstEstado) {
		this.dstEstado = dstEstado;
	}

}
