package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Falta generated by hbm2java
 */
@Entity
@Table(name = "FALTA", schema = "BDTALENTOHUMANO")
public class Falta implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int flId;
	private String flNombre;
	private String flDescripcion;
	private BigDecimal flEstado;
	private Set<CategoriaFalta> categoriaFaltas = new HashSet<CategoriaFalta>(0);

	public Falta() {
	}

	public Falta(int flId, String flNombre) {
		this.flId = flId;
		this.flNombre = flNombre;
	}

	public Falta(int flId, String flNombre, String flDescripcion, BigDecimal flEstado,
			Set<CategoriaFalta> categoriaFaltas) {
		this.flId = flId;
		this.flNombre = flNombre;
		this.flDescripcion = flDescripcion;
		this.flEstado = flEstado;
		this.categoriaFaltas = categoriaFaltas;
	}

	@Id

	@Column(name = "FL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getFlId() {
		return this.flId;
	}

	public void setFlId(int flId) {
		this.flId = flId;
	}

	@Column(name = "FL__NOMBRE", nullable = false, length = 512)
	public String getFlNombre() {
		return this.flNombre;
	}

	public void setFlNombre(String flNombre) {
		this.flNombre = flNombre;
	}

	@Column(name = "FL_DESCRIPCION", length = 512)
	public String getFlDescripcion() {
		return this.flDescripcion;
	}

	public void setFlDescripcion(String flDescripcion) {
		this.flDescripcion = flDescripcion;
	}

	@Column(name = "FL_ESTADO", precision = 22, scale = 0)
	public BigDecimal getFlEstado() {
		return this.flEstado;
	}

	public void setFlEstado(BigDecimal flEstado) {
		this.flEstado = flEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "falta")
	public Set<CategoriaFalta> getCategoriaFaltas() {
		return this.categoriaFaltas;
	}

	public void setCategoriaFaltas(Set<CategoriaFalta> categoriaFaltas) {
		this.categoriaFaltas = categoriaFaltas;
	}

}
