package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FichaEmpleado generated by hbm2java
 */
@Entity
@Table(name = "FICHA_EMPLEADO", schema = "BDTALENTOHUMANO")
public class FichaEmpleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int fcemId;
	private Categoria categoria;
	private Persona persona;
	private TipoEmpleado tipoEmpleado;
	private BigDecimal fcemEstado;
	private Set<DetallePuesto> detallePuestos = new HashSet<DetallePuesto>(0);

	public FichaEmpleado() {
	}

	public FichaEmpleado(int fcemId) {
		this.fcemId = fcemId;
	}

	public FichaEmpleado(int fcemId, Categoria categoria, Persona persona, TipoEmpleado tipoEmpleado,
			BigDecimal fcemEstado, Set<DetallePuesto> detallePuestos) {
		this.fcemId = fcemId;
		this.categoria = categoria;
		this.persona = persona;
		this.tipoEmpleado = tipoEmpleado;
		this.fcemEstado = fcemEstado;
		this.detallePuestos = detallePuestos;
	}

	@Id

	@Column(name = "FCEM_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getFcemId() {
		return this.fcemId;
	}

	public void setFcemId(int fcemId) {
		this.fcemId = fcemId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CTG_ID")
	public Categoria getCategoria() {
		return this.categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRS_ID")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TPEM_ID")
	public TipoEmpleado getTipoEmpleado() {
		return this.tipoEmpleado;
	}

	public void setTipoEmpleado(TipoEmpleado tipoEmpleado) {
		this.tipoEmpleado = tipoEmpleado;
	}

	@Column(name = "FCEM_ESTADO", precision = 22, scale = 0)
	public BigDecimal getFcemEstado() {
		return this.fcemEstado;
	}

	public void setFcemEstado(BigDecimal fcemEstado) {
		this.fcemEstado = fcemEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fichaEmpleado")
	public Set<DetallePuesto> getDetallePuestos() {
		return this.detallePuestos;
	}

	public void setDetallePuestos(Set<DetallePuesto> detallePuestos) {
		this.detallePuestos = detallePuestos;
	}

}
