package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Funcion generated by hbm2java
 */
@Entity
@Table(name = "FUNCION", schema = "BDTALENTOHUMANO")
public class Funcion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int fncId;
	private String fncDescripcion;
	private Set<FuncionPuesto> funcionPuestos = new HashSet<FuncionPuesto>(0);

	public Funcion() {
	}

	public Funcion(int fncId) {
		this.fncId = fncId;
	}

	public Funcion(int fncId, String fncDescripcion, Set<FuncionPuesto> funcionPuestos) {
		this.fncId = fncId;
		this.fncDescripcion = fncDescripcion;
		this.funcionPuestos = funcionPuestos;
	}

	@Id

	@Column(name = "FNC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getFncId() {
		return this.fncId;
	}

	public void setFncId(int fncId) {
		this.fncId = fncId;
	}

	@Column(name = "FNC_DESCRIPCION", length = 256)
	public String getFncDescripcion() {
		return this.fncDescripcion;
	}

	public void setFncDescripcion(String fncDescripcion) {
		this.fncDescripcion = fncDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "funcion")
	public Set<FuncionPuesto> getFuncionPuestos() {
		return this.funcionPuestos;
	}

	public void setFuncionPuestos(Set<FuncionPuesto> funcionPuestos) {
		this.funcionPuestos = funcionPuestos;
	}

}
