package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FuncionPuesto generated by hbm2java
 */
@Entity
@Table(name = "FUNCION_PUESTO", schema = "BDTALENTOHUMANO")
public class FuncionPuesto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int fnpsId;
	private Funcion funcion;
	private Puesto puesto;

	public FuncionPuesto() {
	}

	public FuncionPuesto(int fnpsId) {
		this.fnpsId = fnpsId;
	}

	public FuncionPuesto(int fnpsId, Funcion funcion, Puesto puesto) {
		this.fnpsId = fnpsId;
		this.funcion = funcion;
		this.puesto = puesto;
	}

	@Id

	@Column(name = "FNPS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getFnpsId() {
		return this.fnpsId;
	}

	public void setFnpsId(int fnpsId) {
		this.fnpsId = fnpsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FNC_ID")
	public Funcion getFuncion() {
		return this.funcion;
	}

	public void setFuncion(Funcion funcion) {
		this.funcion = funcion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PST_ID")
	public Puesto getPuesto() {
		return this.puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}

}
