package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistorialDescuento generated by hbm2java
 */
@Entity
@Table(name = "HISTORIAL_DESCUENTO", schema = "BDTALENTOHUMANO")
public class HistorialDescuento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int hsdsId;
	private AcrDsc acrDsc;
	private RolPago rolPago;
	private BigDecimal hsdsPorcentaje;
	private BigDecimal hsdsMonto;
	private BigDecimal hsdsTotal;
	private Date hsdsFecha;
	private String hsdsObservacion;
	private String hsdsCodigoFuncionario;
	private BigDecimal hsdsDtpsId;
	private BigDecimal hsdsEstado;

	public HistorialDescuento() {
	}

	public HistorialDescuento(int hsdsId) {
		this.hsdsId = hsdsId;
	}

	public HistorialDescuento(int hsdsId, AcrDsc acrDsc, RolPago rolPago, BigDecimal hsdsPorcentaje,
			BigDecimal hsdsMonto, BigDecimal hsdsTotal, Date hsdsFecha, String hsdsObservacion,
			String hsdsCodigoFuncionario, BigDecimal hsdsDtpsId, BigDecimal hsdsEstado) {
		this.hsdsId = hsdsId;
		this.acrDsc = acrDsc;
		this.rolPago = rolPago;
		this.hsdsPorcentaje = hsdsPorcentaje;
		this.hsdsMonto = hsdsMonto;
		this.hsdsTotal = hsdsTotal;
		this.hsdsFecha = hsdsFecha;
		this.hsdsObservacion = hsdsObservacion;
		this.hsdsCodigoFuncionario = hsdsCodigoFuncionario;
		this.hsdsDtpsId = hsdsDtpsId;
		this.hsdsEstado = hsdsEstado;
	}

	@Id

	@Column(name = "HSDS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getHsdsId() {
		return this.hsdsId;
	}

	public void setHsdsId(int hsdsId) {
		this.hsdsId = hsdsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ACDS_ID")
	public AcrDsc getAcrDsc() {
		return this.acrDsc;
	}

	public void setAcrDsc(AcrDsc acrDsc) {
		this.acrDsc = acrDsc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROL_PAG_ID")
	public RolPago getRolPago() {
		return this.rolPago;
	}

	public void setRolPago(RolPago rolPago) {
		this.rolPago = rolPago;
	}

	@Column(name = "HSDS_PORCENTAJE", precision = 4)
	public BigDecimal getHsdsPorcentaje() {
		return this.hsdsPorcentaje;
	}

	public void setHsdsPorcentaje(BigDecimal hsdsPorcentaje) {
		this.hsdsPorcentaje = hsdsPorcentaje;
	}

	@Column(name = "HSDS_MONTO", precision = 4)
	public BigDecimal getHsdsMonto() {
		return this.hsdsMonto;
	}

	public void setHsdsMonto(BigDecimal hsdsMonto) {
		this.hsdsMonto = hsdsMonto;
	}

	@Column(name = "HSDS_TOTAL", precision = 4)
	public BigDecimal getHsdsTotal() {
		return this.hsdsTotal;
	}

	public void setHsdsTotal(BigDecimal hsdsTotal) {
		this.hsdsTotal = hsdsTotal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "HSDS_FECHA", length = 7)
	public Date getHsdsFecha() {
		return this.hsdsFecha;
	}

	public void setHsdsFecha(Date hsdsFecha) {
		this.hsdsFecha = hsdsFecha;
	}

	@Column(name = "HSDS_OBSERVACION")
	public String getHsdsObservacion() {
		return this.hsdsObservacion;
	}

	public void setHsdsObservacion(String hsdsObservacion) {
		this.hsdsObservacion = hsdsObservacion;
	}

	@Column(name = "HSDS_CODIGO_FUNCIONARIO", length = 8)
	public String getHsdsCodigoFuncionario() {
		return this.hsdsCodigoFuncionario;
	}

	public void setHsdsCodigoFuncionario(String hsdsCodigoFuncionario) {
		this.hsdsCodigoFuncionario = hsdsCodigoFuncionario;
	}

	@Column(name = "HSDS_DTPS_ID", precision = 22, scale = 0)
	public BigDecimal getHsdsDtpsId() {
		return this.hsdsDtpsId;
	}

	public void setHsdsDtpsId(BigDecimal hsdsDtpsId) {
		this.hsdsDtpsId = hsdsDtpsId;
	}

	@Column(name = "HSDS_ESTADO", precision = 22, scale = 0)
	public BigDecimal getHsdsEstado() {
		return this.hsdsEstado;
	}

	public void setHsdsEstado(BigDecimal hsdsEstado) {
		this.hsdsEstado = hsdsEstado;
	}

}
