package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InstruccionPuesto generated by hbm2java
 */
@Entity
@Table(name = "INSTRUCCION_PUESTO", schema = "BDTALENTOHUMANO")
public class InstruccionPuesto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int inpsId;
	private NivelInstruccion nivelInstruccion;
	private Puesto puesto;
	private BigDecimal inpsAnio;
	private BigDecimal inpsMes;

	public InstruccionPuesto() {
	}

	public InstruccionPuesto(int inpsId) {
		this.inpsId = inpsId;
	}

	public InstruccionPuesto(int inpsId, NivelInstruccion nivelInstruccion, Puesto puesto, BigDecimal inpsAnio,
			BigDecimal inpsMes) {
		this.inpsId = inpsId;
		this.nivelInstruccion = nivelInstruccion;
		this.puesto = puesto;
		this.inpsAnio = inpsAnio;
		this.inpsMes = inpsMes;
	}

	@Id

	@Column(name = "INPS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getInpsId() {
		return this.inpsId;
	}

	public void setInpsId(int inpsId) {
		this.inpsId = inpsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NVIN_ID")
	public NivelInstruccion getNivelInstruccion() {
		return this.nivelInstruccion;
	}

	public void setNivelInstruccion(NivelInstruccion nivelInstruccion) {
		this.nivelInstruccion = nivelInstruccion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PST_ID")
	public Puesto getPuesto() {
		return this.puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}

	@Column(name = "INPS_ANIO", precision = 22, scale = 0)
	public BigDecimal getInpsAnio() {
		return this.inpsAnio;
	}

	public void setInpsAnio(BigDecimal inpsAnio) {
		this.inpsAnio = inpsAnio;
	}

	@Column(name = "INPS_MES", precision = 22, scale = 0)
	public BigDecimal getInpsMes() {
		return this.inpsMes;
	}

	public void setInpsMes(BigDecimal inpsMes) {
		this.inpsMes = inpsMes;
	}

}
