package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NivelInstruccion generated by hbm2java
 */
@Entity
@Table(name = "NIVEL_INSTRUCCION", schema = "BDTALENTOHUMANO")
public class NivelInstruccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int nvinId;
	private String nvinDescripcion;
	private Set<InstruccionPuesto> instruccionPuestos = new HashSet<InstruccionPuesto>(0);

	public NivelInstruccion() {
	}

	public NivelInstruccion(int nvinId) {
		this.nvinId = nvinId;
	}

	public NivelInstruccion(int nvinId, String nvinDescripcion, Set<InstruccionPuesto> instruccionPuestos) {
		this.nvinId = nvinId;
		this.nvinDescripcion = nvinDescripcion;
		this.instruccionPuestos = instruccionPuestos;
	}

	@Id

	@Column(name = "NVIN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getNvinId() {
		return this.nvinId;
	}

	public void setNvinId(int nvinId) {
		this.nvinId = nvinId;
	}

	@Column(name = "NVIN_DESCRIPCION", length = 256)
	public String getNvinDescripcion() {
		return this.nvinDescripcion;
	}

	public void setNvinDescripcion(String nvinDescripcion) {
		this.nvinDescripcion = nvinDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelInstruccion")
	public Set<InstruccionPuesto> getInstruccionPuestos() {
		return this.instruccionPuestos;
	}

	public void setInstruccionPuestos(Set<InstruccionPuesto> instruccionPuestos) {
		this.instruccionPuestos = instruccionPuestos;
	}

}
