package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * NivelCompetencia generated by hbm2java
 */
@Entity
@Table(name = "NIVEL_COMPETENCIA", schema = "BDTALENTOHUMANO")
public class NivelCompetencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int nvcmId;
	private Competencia competencia;
	private BigDecimal nvcmDescripcion;
	private String nvcmComportamiento;
	private Set<CompetenciaPuesto> competenciaPuestos = new HashSet<CompetenciaPuesto>(0);

	public NivelCompetencia() {
	}

	public NivelCompetencia(int nvcmId) {
		this.nvcmId = nvcmId;
	}

	public NivelCompetencia(int nvcmId, Competencia competencia, BigDecimal nvcmDescripcion, String nvcmComportamiento,
			Set<CompetenciaPuesto> competenciaPuestos) {
		this.nvcmId = nvcmId;
		this.competencia = competencia;
		this.nvcmDescripcion = nvcmDescripcion;
		this.nvcmComportamiento = nvcmComportamiento;
		this.competenciaPuestos = competenciaPuestos;
	}

	@Id

	@Column(name = "NVCM_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getNvcmId() {
		return this.nvcmId;
	}

	public void setNvcmId(int nvcmId) {
		this.nvcmId = nvcmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CMP_ID")
	public Competencia getCompetencia() {
		return this.competencia;
	}

	public void setCompetencia(Competencia competencia) {
		this.competencia = competencia;
	}

	@Column(name = "NVCM_DESCRIPCION", precision = 22, scale = 0)
	public BigDecimal getNvcmDescripcion() {
		return this.nvcmDescripcion;
	}

	public void setNvcmDescripcion(BigDecimal nvcmDescripcion) {
		this.nvcmDescripcion = nvcmDescripcion;
	}

	@Column(name = "NVCM_COMPORTAMIENTO", length = 512)
	public String getNvcmComportamiento() {
		return this.nvcmComportamiento;
	}

	public void setNvcmComportamiento(String nvcmComportamiento) {
		this.nvcmComportamiento = nvcmComportamiento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelCompetencia")
	public Set<CompetenciaPuesto> getCompetenciaPuestos() {
		return this.competenciaPuestos;
	}

	public void setCompetenciaPuestos(Set<CompetenciaPuesto> competenciaPuestos) {
		this.competenciaPuestos = competenciaPuestos;
	}

}
