package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ParametroVacaciones generated by hbm2java
 */
@Entity
@Table(name = "PARAMETRO_VACACIONES", schema = "BDTALENTOHUMANO")
public class ParametroVacaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int prvcId;
	private BigDecimal numdias;
	private BigDecimal prvcVariacionAnos;
	private BigDecimal prvcVariacionDias;
	private BigDecimal prvCEstado;
	private Set<Regimen> regimens = new HashSet<Regimen>(0);

	public ParametroVacaciones() {
	}

	public ParametroVacaciones(int prvcId) {
		this.prvcId = prvcId;
	}

	public ParametroVacaciones(int prvcId, BigDecimal numdias, BigDecimal prvcVariacionAnos,
			BigDecimal prvcVariacionDias, BigDecimal prvCEstado, Set<Regimen> regimens) {
		this.prvcId = prvcId;
		this.numdias = numdias;
		this.prvcVariacionAnos = prvcVariacionAnos;
		this.prvcVariacionDias = prvcVariacionDias;
		this.prvCEstado = prvCEstado;
		this.regimens = regimens;
	}

	@Id

	@Column(name = "PRVC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrvcId() {
		return this.prvcId;
	}

	public void setPrvcId(int prvcId) {
		this.prvcId = prvcId;
	}

	@Column(name = "NUMDIAS", precision = 22, scale = 0)
	public BigDecimal getNumdias() {
		return this.numdias;
	}

	public void setNumdias(BigDecimal numdias) {
		this.numdias = numdias;
	}

	@Column(name = "PRVC_VARIACION_ANOS", precision = 22, scale = 0)
	public BigDecimal getPrvcVariacionAnos() {
		return this.prvcVariacionAnos;
	}

	public void setPrvcVariacionAnos(BigDecimal prvcVariacionAnos) {
		this.prvcVariacionAnos = prvcVariacionAnos;
	}

	@Column(name = "PRVC_VARIACION_DIAS", precision = 22, scale = 0)
	public BigDecimal getPrvcVariacionDias() {
		return this.prvcVariacionDias;
	}

	public void setPrvcVariacionDias(BigDecimal prvcVariacionDias) {
		this.prvcVariacionDias = prvcVariacionDias;
	}

	@Column(name = "PRV_C_ESTADO", precision = 22, scale = 0)
	public BigDecimal getPrvCEstado() {
		return this.prvCEstado;
	}

	public void setPrvCEstado(BigDecimal prvCEstado) {
		this.prvCEstado = prvCEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parametroVacaciones")
	public Set<Regimen> getRegimens() {
		return this.regimens;
	}

	public void setRegimens(Set<Regimen> regimens) {
		this.regimens = regimens;
	}

}
