package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import javax.persistence.OneToMany;
import javax.persistence.Table;


/**
 * ParametroVacaciones generated by hbm2java
 */
@Entity
@Table(name = "PARAMETRO_VACACIONES", schema = "BDTALENTOHUMANO")
public class ParametroVacaciones implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int prvcId;
	private String prvcNombres;
	private String  prvcValor;
	private String prvcDescripcion; 
	private BigDecimal prvCEstado;
	private List<ParametroVacacionRegimen> parametroVacacionesRegimens=  new ArrayList<>();

	public ParametroVacaciones() {
	}

	public ParametroVacaciones(int prvcId) {
		this.prvcId = prvcId;
	}

	public ParametroVacaciones(int prvcId,String prvcNombres, String  prvcValor, String prvcDescripcion, BigDecimal prvCEstado) {
		this.prvcId = prvcId;
		this.prvcNombres = prvcNombres;
		this.prvcValor = prvcValor;
		this.prvcDescripcion = prvcDescripcion;
		this.prvCEstado = prvCEstado;
		
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY) 
	@Column(name = "PRVC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrvcId() {
		return this.prvcId;
	}

	public void setPrvcId(int prvcId) {
		this.prvcId = prvcId;
	}
	

	@Column(name = "PRVC_NOMBRE")
	public String getPrvcNombres() {
		return prvcNombres;
	}

	public void setPrvcNombres(String prvcNombres) {
		this.prvcNombres = prvcNombres;
	}
	
	@Column(name = "PRVC_VALOR")
	public String getPrvcValor() {
		return prvcValor;
	}

	public void setPrvcValor(String prvcValor) {
		this.prvcValor = prvcValor;
	}
	
	@Column(name = "PRVC_DESCRIPCION")
	public String getPrvcDescripcion() {
		return prvcDescripcion;
	}

	public void setPrvcDescripcion(String prvcDescripcion) {
		this.prvcDescripcion = prvcDescripcion;
	}

	@Column(name = "PRV_C_ESTADO", precision = 22, scale = 0)
	public BigDecimal getPrvCEstado() {
		return this.prvCEstado;
	}

	public void setPrvCEstado(BigDecimal prvCEstado) {
		this.prvCEstado = prvCEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parametroVacaciones")
	public List<ParametroVacacionRegimen> getParametroVacaciones() {
		return parametroVacacionesRegimens;
	}

	public void setParametroVacaciones(List<ParametroVacacionRegimen> parametroVacacionesRegimens) {
		this.parametroVacacionesRegimens = parametroVacacionesRegimens;
	}

}
