package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Partida generated by hbm2java
 */
@Entity
@Table(name = "PARTIDA", schema = "BDTALENTOHUMANO")
public class Partida implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int prtId;
	private String prtNumero;
	private Set<Distributivo> distributivos = new HashSet<Distributivo>(0);

	public Partida() {
	}

	public Partida(int prtId) {
		this.prtId = prtId;
	}

	public Partida(int prtId, String prtNumero, Set<Distributivo> distributivos) {
		this.prtId = prtId;
		this.prtNumero = prtNumero;
		this.distributivos = distributivos;
	}

	@Id

	@Column(name = "PRT_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrtId() {
		return this.prtId;
	}

	public void setPrtId(int prtId) {
		this.prtId = prtId;
	}

	@Column(name = "PRT_NUMERO", length = 100)
	public String getPrtNumero() {
		return this.prtNumero;
	}

	public void setPrtNumero(String prtNumero) {
		this.prtNumero = prtNumero;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "partida")
	public Set<Distributivo> getDistributivos() {
		return this.distributivos;
	}

	public void setDistributivos(Set<Distributivo> distributivos) {
		this.distributivos = distributivos;
	}

}
