package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persona generated by hbm2java
 */
@Entity
@Table(name = "PERSONA", schema = "BDTALENTOHUMANO")
public class Persona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int prsId;
	private Etnia etnia;
	private BigDecimal prsTipoIdentificacion;
	private BigDecimal prsTipoIdentificacionSniese;
	private String prsIdentificacion;
	private String prsPrimerApellido;
	private String prsSegundoApellido;
	private String prsNombres;
	private BigDecimal prsSexo;
	private BigDecimal prsSexoSniese;
	private String prsMailPersonal;
	private String prsMailInstitucional;
	private String prsTelefono;
	private Date prsFechaNacimiento;
	private List<FichaEmpleado> fichaEmpleados = new ArrayList<FichaEmpleado>();
	private List<Usuario> usuarios = new ArrayList<Usuario>();

	public Persona() {
	}

	public Persona(int prsId) {
		this.prsId = prsId;
	}

	public Persona(int prsId, Etnia etnia, BigDecimal prsTipoIdentificacion, BigDecimal prsTipoIdentificacionSniese,
			String prsIdentificacion, String prsPrimerApellido, String prsSegundoApellido, String prsNombres,
			BigDecimal prsSexo, BigDecimal prsSexoSniese, String prsMailPersonal, String prsMailInstitucional,
			String prsTelefono, Date prsFechaNacimiento, List<FichaEmpleado> fichaEmpleados, List<Usuario> usuarios) {
		this.prsId = prsId;
		this.etnia = etnia;
		this.prsTipoIdentificacion = prsTipoIdentificacion;
		this.prsTipoIdentificacionSniese = prsTipoIdentificacionSniese;
		this.prsIdentificacion = prsIdentificacion;
		this.prsPrimerApellido = prsPrimerApellido;
		this.prsSegundoApellido = prsSegundoApellido;
		this.prsNombres = prsNombres;
		this.prsSexo = prsSexo;
		this.prsSexoSniese = prsSexoSniese;
		this.prsMailPersonal = prsMailPersonal;
		this.prsMailInstitucional = prsMailInstitucional;
		this.prsTelefono = prsTelefono;
		this.prsFechaNacimiento = prsFechaNacimiento;
		this.fichaEmpleados = fichaEmpleados;
		this.usuarios = usuarios;
	}

	@Id

	@Column(name = "PRS_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrsId() {
		return this.prsId;
	}

	public void setPrsId(int prsId) {
		this.prsId = prsId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ETN_ID")
	public Etnia getEtnia() {
		return this.etnia;
	}

	public void setEtnia(Etnia etnia) {
		this.etnia = etnia;
	}

	@Column(name = "PRS_TIPO_IDENTIFICACION", precision = 22, scale = 0)
	public BigDecimal getPrsTipoIdentificacion() {
		return this.prsTipoIdentificacion;
	}

	public void setPrsTipoIdentificacion(BigDecimal prsTipoIdentificacion) {
		this.prsTipoIdentificacion = prsTipoIdentificacion;
	}

	@Column(name = "PRS_TIPO_IDENTIFICACION_SNIESE", precision = 22, scale = 0)
	public BigDecimal getPrsTipoIdentificacionSniese() {
		return this.prsTipoIdentificacionSniese;
	}

	public void setPrsTipoIdentificacionSniese(BigDecimal prsTipoIdentificacionSniese) {
		this.prsTipoIdentificacionSniese = prsTipoIdentificacionSniese;
	}

	@Column(name = "PRS_IDENTIFICACION", length = 13, nullable = false )
	public String getPrsIdentificacion() {
		return this.prsIdentificacion;
	}

	public void setPrsIdentificacion(String prsIdentificacion) {
		this.prsIdentificacion = prsIdentificacion;
	}

	@Column(name = "PRS_PRIMER_APELLIDO", length = 32)
	public String getPrsPrimerApellido() {
		return this.prsPrimerApellido;
	}

	public void setPrsPrimerApellido(String prsPrimerApellido) {
		this.prsPrimerApellido = prsPrimerApellido;
	}

	@Column(name = "PRS_SEGUNDO_APELLIDO", length = 32)
	public String getPrsSegundoApellido() {
		return this.prsSegundoApellido;
	}

	public void setPrsSegundoApellido(String prsSegundoApellido) {
		this.prsSegundoApellido = prsSegundoApellido;
	}

	@Column(name = "PRS_NOMBRES", length = 50)
	public String getPrsNombres() {
		return this.prsNombres;
	}

	public void setPrsNombres(String prsNombres) {
		this.prsNombres = prsNombres;
	}

	@Column(name = "PRS_SEXO", precision = 22, scale = 0)
	public BigDecimal getPrsSexo() {
		return this.prsSexo;
	}

	public void setPrsSexo(BigDecimal prsSexo) {
		this.prsSexo = prsSexo;
	}

	@Column(name = "PRS_SEXO_SNIESE", precision = 22, scale = 0)
	public BigDecimal getPrsSexoSniese() {
		return this.prsSexoSniese;
	}

	public void setPrsSexoSniese(BigDecimal prsSexoSniese) {
		this.prsSexoSniese = prsSexoSniese;
	}

	@Column(name = "PRS_MAIL_PERSONAL", length = 50)
	public String getPrsMailPersonal() {
		return this.prsMailPersonal;
	}

	public void setPrsMailPersonal(String prsMailPersonal) {
		this.prsMailPersonal = prsMailPersonal;
	}

	@Column(name = "PRS_MAIL_INSTITUCIONAL", length = 50)
	public String getPrsMailInstitucional() {
		return this.prsMailInstitucional;
	}

	public void setPrsMailInstitucional(String prsMailInstitucional) {
		this.prsMailInstitucional = prsMailInstitucional;
	}

	@Column(name = "PRS_TELEFONO", length = 10)
	public String getPrsTelefono() {
		return this.prsTelefono;
	}

	public void setPrsTelefono(String prsTelefono) {
		this.prsTelefono = prsTelefono;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "PRS_FECHA_NACIMIENTO", length = 7)
	public Date getPrsFechaNacimiento() {
		return this.prsFechaNacimiento;
	}

	public void setPrsFechaNacimiento(Date prsFechaNacimiento) {
		this.prsFechaNacimiento = prsFechaNacimiento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public List<FichaEmpleado> getFichaEmpleados() {
		return this.fichaEmpleados;
	}

	public void setFichaEmpleados(List<FichaEmpleado> fichaEmpleados) {
		this.fichaEmpleados = fichaEmpleados;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "persona")
	public List<Usuario> getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(List<Usuario> usuarios) {
		this.usuarios = usuarios;
	}

	@Override
	public String toString() {
		return "" + prsPrimerApellido + " " + prsSegundoApellido+ "";
	}
	
	

}
