package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proceso generated by hbm2java
 */
@Entity
@Table(name = "PROCESO", schema = "BDTALENTOHUMANO")
public class Proceso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int prcId;
	private String prcDescripcion;
	private Set<Serie> series = new HashSet<Serie>(0);

	public Proceso() {
	}

	public Proceso(int prcId) {
		this.prcId = prcId;
	}

	public Proceso(int prcId, String prcDescripcion, Set<Serie> series) {
		this.prcId = prcId;
		this.prcDescripcion = prcDescripcion;
		this.series = series;
	}

	@Id

	@Column(name = "PRC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPrcId() {
		return this.prcId;
	}

	public void setPrcId(int prcId) {
		this.prcId = prcId;
	}

	@Column(name = "PRC_DESCRIPCION", length = 256)
	public String getPrcDescripcion() {
		return this.prcDescripcion;
	}

	public void setPrcDescripcion(String prcDescripcion) {
		this.prcDescripcion = prcDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "proceso")
	public Set<Serie> getSeries() {
		return this.series;
	}

	public void setSeries(Set<Serie> series) {
		this.series = series;
	}

}
