package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PuestoAreaConocimiento generated by hbm2java
 */
@Entity
@Table(name = "PUESTO_AREA_CONOCIMIENTO", schema = "BDTALENTOHUMANO")
public class PuestoAreaConocimiento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int psarcnId;
	private AreaConocimiento areaConocimiento;
	private Puesto puesto;

	public PuestoAreaConocimiento() {
	}

	public PuestoAreaConocimiento(int psarcnId) {
		this.psarcnId = psarcnId;
	}

	public PuestoAreaConocimiento(int psarcnId, AreaConocimiento areaConocimiento, Puesto puesto) {
		this.psarcnId = psarcnId;
		this.areaConocimiento = areaConocimiento;
		this.puesto = puesto;
	}

	@Id

	@Column(name = "PSARCN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPsarcnId() {
		return this.psarcnId;
	}

	public void setPsarcnId(int psarcnId) {
		this.psarcnId = psarcnId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ARCN_ID")
	public AreaConocimiento getAreaConocimiento() {
		return this.areaConocimiento;
	}

	public void setAreaConocimiento(AreaConocimiento areaConocimiento) {
		this.areaConocimiento = areaConocimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PST_ID")
	public Puesto getPuesto() {
		return this.puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}

}
