package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.ArrayList;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Puesto generated by hbm2java
 */
@Entity
@Table(name = "PUESTO", schema = "BDTALENTOHUMANO")
public class Puesto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int pstId;
	private GrupoOcupacional grupoOcupacional;
	private Serie serie;
	private String pstDenominacion;
	private BigDecimal pstEstado;
	private BigDecimal pstAmbito;
	private BigDecimal pstNivel;
	private String pstMision;
	private String pstResponsabilidad;
	private BigDecimal pstInstruccion;
	private BigDecimal pstTiempoExperiencia;
	private String pstDescripcionExperiencia;
	private String pstInterfaz;
	private List<FuncionPuesto> funcionPuestos = new ArrayList<>();
	private List<ActividadPuesto> actividadPuestos =  new ArrayList<>();
	private List<CompetenciaPuesto> competenciaPuestos =  new ArrayList<>();
	private List<Tramite> tramites =  new ArrayList<>(); 
	private List<InstruccionPuesto> instruccionPuestos = new ArrayList<>();
	private List<DestrezaPuesto> destrezaPuestos =  new ArrayList<>(); 
	private List<DetallePuesto> detallePuestos =  new ArrayList<>();
	private List<PuestoAreaConocimiento> puestoAreaConocimientos =  new ArrayList<>();
	private List<ConocimientoPuesto> conocimientoPuestos =  new ArrayList<>();

	public Puesto() {
	}

	public Puesto(int pstId) {
		this.pstId = pstId;
	}

	public Puesto(int pstId, GrupoOcupacional grupoOcupacional, Serie serie, String pstDenominacion,
			BigDecimal pstEstado, BigDecimal pstAmbito, BigDecimal pstNivel, String pstMision,
			String pstResponsabilidad, BigDecimal pstInstruccion, BigDecimal pstTiempoExperiencia,
			String pstDescripcionExperiencia, String pstInterfaz, List<FuncionPuesto> funcionPuestos,
			List<ActividadPuesto> actividadPuestos, List<CompetenciaPuesto> competenciaPuestos, List<Tramite> tramites,
			List<InstruccionPuesto> instruccionPuestos, List<DestrezaPuesto> destrezaPuestos,
			List<DetallePuesto> detallePuestos, List<PuestoAreaConocimiento> puestoAreaConocimientos,
			List<ConocimientoPuesto> conocimientoPuestos) {
		this.pstId = pstId;
		this.grupoOcupacional = grupoOcupacional;
		this.serie = serie;
		this.pstDenominacion = pstDenominacion;
		this.pstEstado = pstEstado;
		this.pstAmbito = pstAmbito;
		this.pstNivel = pstNivel;
		this.pstMision = pstMision;
		this.pstResponsabilidad = pstResponsabilidad;
		this.pstInstruccion = pstInstruccion;
		this.pstTiempoExperiencia = pstTiempoExperiencia;
		this.pstDescripcionExperiencia = pstDescripcionExperiencia;
		this.pstInterfaz = pstInterfaz;
		this.funcionPuestos = funcionPuestos;
		this.actividadPuestos = actividadPuestos;
		this.competenciaPuestos = competenciaPuestos;
		this.tramites = tramites;
		this.instruccionPuestos = instruccionPuestos;
		this.destrezaPuestos = destrezaPuestos;
		this.detallePuestos = detallePuestos;
		this.puestoAreaConocimientos = puestoAreaConocimientos;
		this.conocimientoPuestos = conocimientoPuestos;
	}

	@Id

	@Column(name = "PST_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPstId() {
		return this.pstId;
	}

	public void setPstId(int pstId) {
		this.pstId = pstId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROC_ID")
	public GrupoOcupacional getGrupoOcupacional() {
		return this.grupoOcupacional;
	}

	public void setGrupoOcupacional(GrupoOcupacional grupoOcupacional) {
		this.grupoOcupacional = grupoOcupacional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SER_ID")
	public Serie getSerie() {
		return this.serie;
	}

	public void setSerie(Serie serie) {
		this.serie = serie;
	}

	@Column(name = "PST_DENOMINACION", length = 256)
	public String getPstDenominacion() {
		return this.pstDenominacion;
	}

	public void setPstDenominacion(String pstDenominacion) {
		this.pstDenominacion = pstDenominacion;
	}

	@Column(name = "PST_ESTADO", precision = 22, scale = 0)
	public BigDecimal getPstEstado() {
		return this.pstEstado;
	}

	public void setPstEstado(BigDecimal pstEstado) {
		this.pstEstado = pstEstado;
	}

	@Column(name = "PST_AMBITO", precision = 22, scale = 0)
	public BigDecimal getPstAmbito() {
		return this.pstAmbito;
	}

	public void setPstAmbito(BigDecimal pstAmbito) {
		this.pstAmbito = pstAmbito;
	}

	@Column(name = "PST_NIVEL", precision = 22, scale = 0)
	public BigDecimal getPstNivel() {
		return this.pstNivel;
	}

	public void setPstNivel(BigDecimal pstNivel) {
		this.pstNivel = pstNivel;
	}

	@Column(name = "PST_MISION", length = 512)
	public String getPstMision() {
		return this.pstMision;
	}

	public void setPstMision(String pstMision) {
		this.pstMision = pstMision;
	}

	@Column(name = "PST_RESPONSABILIDAD", length = 512)
	public String getPstResponsabilidad() {
		return this.pstResponsabilidad;
	}

	public void setPstResponsabilidad(String pstResponsabilidad) {
		this.pstResponsabilidad = pstResponsabilidad;
	}

	@Column(name = "PST_INSTRUCCION", precision = 22, scale = 0)
	public BigDecimal getPstInstruccion() {
		return this.pstInstruccion;
	}

	public void setPstInstruccion(BigDecimal pstInstruccion) {
		this.pstInstruccion = pstInstruccion;
	}

	@Column(name = "PST_TIEMPO_EXPERIENCIA", precision = 22, scale = 0)
	public BigDecimal getPstTiempoExperiencia() {
		return this.pstTiempoExperiencia;
	}

	public void setPstTiempoExperiencia(BigDecimal pstTiempoExperiencia) {
		this.pstTiempoExperiencia = pstTiempoExperiencia;
	}

	@Column(name = "PST_DESCRIPCION_EXPERIENCIA", length = 512)
	public String getPstDescripcionExperiencia() {
		return this.pstDescripcionExperiencia;
	}

	public void setPstDescripcionExperiencia(String pstDescripcionExperiencia) {
		this.pstDescripcionExperiencia = pstDescripcionExperiencia;
	}

	@Column(name = "PST_INTERFAZ", length = 512)
	public String getPstInterfaz() {
		return this.pstInterfaz;
	}

	public void setPstInterfaz(String pstInterfaz) {
		this.pstInterfaz = pstInterfaz;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public List<FuncionPuesto> getFuncionPuestos() {
		return this.funcionPuestos;
	}

	public void setFuncionPuestos(List<FuncionPuesto> funcionPuestos) {
		this.funcionPuestos = funcionPuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public List<ActividadPuesto> getActividadPuestos() {
		return this.actividadPuestos;
	}

	public void setActividadPuestos(List<ActividadPuesto> actividadPuestos) {
		this.actividadPuestos = actividadPuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public List<CompetenciaPuesto> getCompetenciaPuestos() {
		return this.competenciaPuestos;
	}

	public void setCompetenciaPuestos(List<CompetenciaPuesto> competenciaPuestos) {
		this.competenciaPuestos = competenciaPuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public List<Tramite> getTramites() {
		return this.tramites;
	}

	public void setTramites(List<Tramite> tramites) {
		this.tramites = tramites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public List<InstruccionPuesto> getInstruccionPuestos() {
		return this.instruccionPuestos;
	}

	public void setInstruccionPuestos(List<InstruccionPuesto> instruccionPuestos) {
		this.instruccionPuestos = instruccionPuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public List<DestrezaPuesto> getDestrezaPuestos() {
		return this.destrezaPuestos;
	}

	public void setDestrezaPuestos(List<DestrezaPuesto> destrezaPuestos) {
		this.destrezaPuestos = destrezaPuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public List<DetallePuesto> getDetallePuestos() {
		return this.detallePuestos;
	}

	public void setDetallePuestos(List<DetallePuesto> detallePuestos) {
		this.detallePuestos = detallePuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public List<PuestoAreaConocimiento> getPuestoAreaConocimientos() {
		return this.puestoAreaConocimientos;
	}

	public void setPuestoAreaConocimientos(List<PuestoAreaConocimiento> puestoAreaConocimientos) {
		this.puestoAreaConocimientos = puestoAreaConocimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public List<ConocimientoPuesto> getConocimientoPuestos() {
		return this.conocimientoPuestos;
	}

	public void setConocimientoPuestos(List<ConocimientoPuesto> conocimientoPuestos) {
		this.conocimientoPuestos = conocimientoPuestos;
	}

}
