package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Puesto generated by hbm2java
 */
@Entity
@Table(name = "PUESTO", schema = "BDTALENTOHUMANO")
public class Puesto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int pstId;
	private GrupoOcupacional grupoOcupacional;
	private Serie serie;
	private String pstDenominacion;
	private BigDecimal pstEstado;
	private BigDecimal pstAmbito;
	private BigDecimal pstNivel;
	private String pstMision;
	private String pstResponsabilidad;
	private BigDecimal pstInstruccion;
	private BigDecimal pstTiempoExperiencia;
	private String pstDescripcionExperiencia;
	private String pstInterfaz;
	private Set<FuncionPuesto> funcionPuestos = new HashSet<FuncionPuesto>(0);
	private Set<ActividadPuesto> actividadPuestos = new HashSet<ActividadPuesto>(0);
	private Set<CompetenciaPuesto> competenciaPuestos = new HashSet<CompetenciaPuesto>(0);
	private Set<Tramite> tramites = new HashSet<Tramite>(0);
	private Set<InstruccionPuesto> instruccionPuestos = new HashSet<InstruccionPuesto>(0);
	private Set<DestrezaPuesto> destrezaPuestos = new HashSet<DestrezaPuesto>(0);
	private Set<DetallePuesto> detallePuestos = new HashSet<DetallePuesto>(0);
	private Set<PuestoAreaConocimiento> puestoAreaConocimientos = new HashSet<PuestoAreaConocimiento>(0);
	private Set<ConocimientoPuesto> conocimientoPuestos = new HashSet<ConocimientoPuesto>(0);

	public Puesto() {
	}

	public Puesto(int pstId) {
		this.pstId = pstId;
	}

	public Puesto(int pstId, GrupoOcupacional grupoOcupacional, Serie serie, String pstDenominacion,
			BigDecimal pstEstado, BigDecimal pstAmbito, BigDecimal pstNivel, String pstMision,
			String pstResponsabilidad, BigDecimal pstInstruccion, BigDecimal pstTiempoExperiencia,
			String pstDescripcionExperiencia, String pstInterfaz, Set<FuncionPuesto> funcionPuestos,
			Set<ActividadPuesto> actividadPuestos, Set<CompetenciaPuesto> competenciaPuestos, Set<Tramite> tramites,
			Set<InstruccionPuesto> instruccionPuestos, Set<DestrezaPuesto> destrezaPuestos,
			Set<DetallePuesto> detallePuestos, Set<PuestoAreaConocimiento> puestoAreaConocimientos,
			Set<ConocimientoPuesto> conocimientoPuestos) {
		this.pstId = pstId;
		this.grupoOcupacional = grupoOcupacional;
		this.serie = serie;
		this.pstDenominacion = pstDenominacion;
		this.pstEstado = pstEstado;
		this.pstAmbito = pstAmbito;
		this.pstNivel = pstNivel;
		this.pstMision = pstMision;
		this.pstResponsabilidad = pstResponsabilidad;
		this.pstInstruccion = pstInstruccion;
		this.pstTiempoExperiencia = pstTiempoExperiencia;
		this.pstDescripcionExperiencia = pstDescripcionExperiencia;
		this.pstInterfaz = pstInterfaz;
		this.funcionPuestos = funcionPuestos;
		this.actividadPuestos = actividadPuestos;
		this.competenciaPuestos = competenciaPuestos;
		this.tramites = tramites;
		this.instruccionPuestos = instruccionPuestos;
		this.destrezaPuestos = destrezaPuestos;
		this.detallePuestos = detallePuestos;
		this.puestoAreaConocimientos = puestoAreaConocimientos;
		this.conocimientoPuestos = conocimientoPuestos;
	}

	@Id

	@Column(name = "PST_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getPstId() {
		return this.pstId;
	}

	public void setPstId(int pstId) {
		this.pstId = pstId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROC_ID")
	public GrupoOcupacional getGrupoOcupacional() {
		return this.grupoOcupacional;
	}

	public void setGrupoOcupacional(GrupoOcupacional grupoOcupacional) {
		this.grupoOcupacional = grupoOcupacional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SER_ID")
	public Serie getSerie() {
		return this.serie;
	}

	public void setSerie(Serie serie) {
		this.serie = serie;
	}

	@Column(name = "PST_DENOMINACION", length = 256)
	public String getPstDenominacion() {
		return this.pstDenominacion;
	}

	public void setPstDenominacion(String pstDenominacion) {
		this.pstDenominacion = pstDenominacion;
	}

	@Column(name = "PST_ESTADO", precision = 22, scale = 0)
	public BigDecimal getPstEstado() {
		return this.pstEstado;
	}

	public void setPstEstado(BigDecimal pstEstado) {
		this.pstEstado = pstEstado;
	}

	@Column(name = "PST_AMBITO", precision = 22, scale = 0)
	public BigDecimal getPstAmbito() {
		return this.pstAmbito;
	}

	public void setPstAmbito(BigDecimal pstAmbito) {
		this.pstAmbito = pstAmbito;
	}

	@Column(name = "PST_NIVEL", precision = 22, scale = 0)
	public BigDecimal getPstNivel() {
		return this.pstNivel;
	}

	public void setPstNivel(BigDecimal pstNivel) {
		this.pstNivel = pstNivel;
	}

	@Column(name = "PST_MISION", length = 512)
	public String getPstMision() {
		return this.pstMision;
	}

	public void setPstMision(String pstMision) {
		this.pstMision = pstMision;
	}

	@Column(name = "PST_RESPONSABILIDAD", length = 512)
	public String getPstResponsabilidad() {
		return this.pstResponsabilidad;
	}

	public void setPstResponsabilidad(String pstResponsabilidad) {
		this.pstResponsabilidad = pstResponsabilidad;
	}

	@Column(name = "PST_INSTRUCCION", precision = 22, scale = 0)
	public BigDecimal getPstInstruccion() {
		return this.pstInstruccion;
	}

	public void setPstInstruccion(BigDecimal pstInstruccion) {
		this.pstInstruccion = pstInstruccion;
	}

	@Column(name = "PST_TIEMPO_EXPERIENCIA", precision = 22, scale = 0)
	public BigDecimal getPstTiempoExperiencia() {
		return this.pstTiempoExperiencia;
	}

	public void setPstTiempoExperiencia(BigDecimal pstTiempoExperiencia) {
		this.pstTiempoExperiencia = pstTiempoExperiencia;
	}

	@Column(name = "PST_DESCRIPCION_EXPERIENCIA", length = 512)
	public String getPstDescripcionExperiencia() {
		return this.pstDescripcionExperiencia;
	}

	public void setPstDescripcionExperiencia(String pstDescripcionExperiencia) {
		this.pstDescripcionExperiencia = pstDescripcionExperiencia;
	}

	@Column(name = "PST_INTERFAZ", length = 512)
	public String getPstInterfaz() {
		return this.pstInterfaz;
	}

	public void setPstInterfaz(String pstInterfaz) {
		this.pstInterfaz = pstInterfaz;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public Set<FuncionPuesto> getFuncionPuestos() {
		return this.funcionPuestos;
	}

	public void setFuncionPuestos(Set<FuncionPuesto> funcionPuestos) {
		this.funcionPuestos = funcionPuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public Set<ActividadPuesto> getActividadPuestos() {
		return this.actividadPuestos;
	}

	public void setActividadPuestos(Set<ActividadPuesto> actividadPuestos) {
		this.actividadPuestos = actividadPuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public Set<CompetenciaPuesto> getCompetenciaPuestos() {
		return this.competenciaPuestos;
	}

	public void setCompetenciaPuestos(Set<CompetenciaPuesto> competenciaPuestos) {
		this.competenciaPuestos = competenciaPuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public Set<Tramite> getTramites() {
		return this.tramites;
	}

	public void setTramites(Set<Tramite> tramites) {
		this.tramites = tramites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public Set<InstruccionPuesto> getInstruccionPuestos() {
		return this.instruccionPuestos;
	}

	public void setInstruccionPuestos(Set<InstruccionPuesto> instruccionPuestos) {
		this.instruccionPuestos = instruccionPuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public Set<DestrezaPuesto> getDestrezaPuestos() {
		return this.destrezaPuestos;
	}

	public void setDestrezaPuestos(Set<DestrezaPuesto> destrezaPuestos) {
		this.destrezaPuestos = destrezaPuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public Set<DetallePuesto> getDetallePuestos() {
		return this.detallePuestos;
	}

	public void setDetallePuestos(Set<DetallePuesto> detallePuestos) {
		this.detallePuestos = detallePuestos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public Set<PuestoAreaConocimiento> getPuestoAreaConocimientos() {
		return this.puestoAreaConocimientos;
	}

	public void setPuestoAreaConocimientos(Set<PuestoAreaConocimiento> puestoAreaConocimientos) {
		this.puestoAreaConocimientos = puestoAreaConocimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "puesto")
	public Set<ConocimientoPuesto> getConocimientoPuestos() {
		return this.conocimientoPuestos;
	}

	public void setConocimientoPuestos(Set<ConocimientoPuesto> conocimientoPuestos) {
		this.conocimientoPuestos = conocimientoPuestos;
	}

}
