package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Regimen generated by hbm2java
 */
@Entity
@Table(name = "REGIMEN", schema = "BDTALENTOHUMANO")
public class Regimen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int rgmId;
	private ParametroVacaciones parametroVacaciones;
	private String rgmDescripcion;
	private String rgmCodigo;
	private BigDecimal rgmEstado;
	private Set<GrupoOcupacional> grupoOcupacionals = new HashSet<GrupoOcupacional>(0);

	public Regimen() {
	}

	public Regimen(int rgmId) {
		this.rgmId = rgmId;
	}

	public Regimen(int rgmId, ParametroVacaciones parametroVacaciones, String rgmDescripcion, String rgmCodigo,
			BigDecimal rgmEstado, Set<GrupoOcupacional> grupoOcupacionals) {
		this.rgmId = rgmId;
		this.parametroVacaciones = parametroVacaciones;
		this.rgmDescripcion = rgmDescripcion;
		this.rgmCodigo = rgmCodigo;
		this.rgmEstado = rgmEstado;
		this.grupoOcupacionals = grupoOcupacionals;
	}

	@Id

	@Column(name = "RGM_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getRgmId() {
		return this.rgmId;
	}

	public void setRgmId(int rgmId) {
		this.rgmId = rgmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRVC_ID")
	public ParametroVacaciones getParametroVacaciones() {
		return this.parametroVacaciones;
	}

	public void setParametroVacaciones(ParametroVacaciones parametroVacaciones) {
		this.parametroVacaciones = parametroVacaciones;
	}

	@Column(name = "RGM_DESCRIPCION", length = 256)
	public String getRgmDescripcion() {
		return this.rgmDescripcion;
	}

	public void setRgmDescripcion(String rgmDescripcion) {
		this.rgmDescripcion = rgmDescripcion;
	}

	@Column(name = "RGM_CODIGO", length = 8)
	public String getRgmCodigo() {
		return this.rgmCodigo;
	}

	public void setRgmCodigo(String rgmCodigo) {
		this.rgmCodigo = rgmCodigo;
	}

	@Column(name = "RGM_ESTADO", precision = 22, scale = 0)
	public BigDecimal getRgmEstado() {
		return this.rgmEstado;
	}

	public void setRgmEstado(BigDecimal rgmEstado) {
		this.rgmEstado = rgmEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "regimen")
	public Set<GrupoOcupacional> getGrupoOcupacionals() {
		return this.grupoOcupacionals;
	}

	public void setGrupoOcupacionals(Set<GrupoOcupacional> grupoOcupacionals) {
		this.grupoOcupacionals = grupoOcupacionals;
	}

}
