package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;



/**
 * RelacionLaboral generated by hbm2java
 */
@Entity
@Table(name = "RELACION_LABORAL", schema = "BDTALENTOHUMANO")
public class RelacionLaboral implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int rllbId;
	private String rllbDescripcion;
	private String rllbEstado;
	private List<DetallePuesto> detallePuestos = new ArrayList<>();

	public RelacionLaboral() {
	}

	public RelacionLaboral(int rllbId) {
		this.rllbId = rllbId;
	}

	public RelacionLaboral(int rllbId, String rllbDescripcion, String rllbEstado, List<DetallePuesto> detallePuestos) {
		this.rllbId = rllbId;
		this.rllbDescripcion = rllbDescripcion;
		this.rllbEstado = rllbEstado;
		this.detallePuestos = detallePuestos;
	}

	@Id

	@Column(name = "RLLB_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getRllbId() {
		return this.rllbId;
	}

	public void setRllbId(int rllbId) {
		this.rllbId = rllbId;
	}

	@Column(name = "RLLB_DESCRIPCION", length = 512)
	public String getRllbDescripcion() {
		return this.rllbDescripcion;
	}

	public void setRllbDescripcion(String rllbDescripcion) {
		this.rllbDescripcion = rllbDescripcion;
	}

	@Column(name = "RLLB_ESTADO", length = 512)
	public String getRllbEstado() {
		return this.rllbEstado;
	}

	public void setRllbEstado(String rllbEstado) {
		this.rllbEstado = rllbEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "relacionLaboral")
	public List<DetallePuesto> getDetallePuestos() {
		return this.detallePuestos;
	}

	public void setDetallePuestos(List<DetallePuesto> detallePuestos) {
		this.detallePuestos = detallePuestos;
	}

}
