package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rol generated by hbm2java
 */
@Entity
@Table(name = "ROL", schema = "BDTALENTOHUMANO")
public class Rol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int rolId;
	private String rolDescripcion;
	private BigDecimal rolTipo;
	private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);

	public Rol() {
	}

	public Rol(int rolId) {
		this.rolId = rolId;
	}

	public Rol(int rolId, String rolDescripcion, BigDecimal rolTipo, Set<UsuarioRol> usuarioRols) {
		this.rolId = rolId;
		this.rolDescripcion = rolDescripcion;
		this.rolTipo = rolTipo;
		this.usuarioRols = usuarioRols;
	}

	@Id

	@Column(name = "ROL_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getRolId() {
		return this.rolId;
	}

	public void setRolId(int rolId) {
		this.rolId = rolId;
	}

	@Column(name = "ROL_DESCRIPCION", length = 20)
	public String getRolDescripcion() {
		return this.rolDescripcion;
	}

	public void setRolDescripcion(String rolDescripcion) {
		this.rolDescripcion = rolDescripcion;
	}

	@Column(name = "ROL_TIPO", precision = 22, scale = 0)
	public BigDecimal getRolTipo() {
		return this.rolTipo;
	}

	public void setRolTipo(BigDecimal rolTipo) {
		this.rolTipo = rolTipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rol")
	public Set<UsuarioRol> getUsuarioRols() {
		return this.usuarioRols;
	}

	public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
		this.usuarioRols = usuarioRols;
	}

}
