package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RolPago generated by hbm2java
 */
@Entity
@Table(name = "ROL_PAGO", schema = "BDTALENTOHUMANO")
public class RolPago implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int rolPagId;
	private ControlPago controlPago;
	private BigDecimal dtpsId;
	private String rolPagCodigoFuncionario;
	private String rolPagFacultad;
	private String rolPagFuncion;
	private BigDecimal rolPagRmu;
	private BigDecimal rolPagFondoReserva;
	private BigDecimal rolPagFondoReservaIess;
	private BigDecimal rolPagAporteIess;
	private BigDecimal rolPagImpuestoRenta;
	private BigDecimal rolPagPrestamoIess;
	private BigDecimal rolPagRetencionJudicial;
	private BigDecimal rolPagAnticipos;
	private BigDecimal rolPagMultas;
	private BigDecimal rolPagVarios;
	private BigDecimal rolPagFondoMortuorio;
	private BigDecimal rolPagCesantiaAdicional;
	private BigDecimal rolPagAsocEmpleados;
	private BigDecimal rolPagAsocProfesores;
	private BigDecimal rolPagAsocFacultad;
	private BigDecimal rolPagFomentoDeporte;
	private BigDecimal rolPagComisariato;
	private BigDecimal rolPagCoopAhoCredDocent;
	private BigDecimal rolPagCesantia;
	private BigDecimal rolPagSeguros;
	private BigDecimal rolPagFondoJubIndexada;
	private BigDecimal rolPagAlimentacion;
	private BigDecimal rolPagTransporte;
	private BigDecimal rolPagCargaFamiliar;
	private BigDecimal rolPagTotalIngreso;
	private BigDecimal rolPagTotalDescuento;
	private BigDecimal rolPagTotalLiquido;
	private BigDecimal rolPagDcmTercero;
	private BigDecimal rolPagDcmCuarto;
	private BigDecimal rolPagDcmTerceroMensual;
	private BigDecimal rolPagDcmCuartoMensual;
	private BigDecimal rolPagPrestamoSindicato;
	private BigDecimal rolPagMes;
	private BigDecimal rolPagAnio;
	private String rolPagPago;
	private BigDecimal rolPagEstado;
	private BigDecimal rolPagCoberturaSaludIess;
	private BigDecimal prsId;
	private Set<HistorialDescuento> historialDescuentos = new HashSet<HistorialDescuento>(0);

	public RolPago() {
	}

	public RolPago(int rolPagId) {
		this.rolPagId = rolPagId;
	}

	public RolPago(int rolPagId, ControlPago controlPago, BigDecimal dtpsId, String rolPagCodigoFuncionario,
			String rolPagFacultad, String rolPagFuncion, BigDecimal rolPagRmu, BigDecimal rolPagFondoReserva,
			BigDecimal rolPagFondoReservaIess, BigDecimal rolPagAporteIess, BigDecimal rolPagImpuestoRenta,
			BigDecimal rolPagPrestamoIess, BigDecimal rolPagRetencionJudicial, BigDecimal rolPagAnticipos,
			BigDecimal rolPagMultas, BigDecimal rolPagVarios, BigDecimal rolPagFondoMortuorio,
			BigDecimal rolPagCesantiaAdicional, BigDecimal rolPagAsocEmpleados, BigDecimal rolPagAsocProfesores,
			BigDecimal rolPagAsocFacultad, BigDecimal rolPagFomentoDeporte, BigDecimal rolPagComisariato,
			BigDecimal rolPagCoopAhoCredDocent, BigDecimal rolPagCesantia, BigDecimal rolPagSeguros,
			BigDecimal rolPagFondoJubIndexada, BigDecimal rolPagAlimentacion, BigDecimal rolPagTransporte,
			BigDecimal rolPagCargaFamiliar, BigDecimal rolPagTotalIngreso, BigDecimal rolPagTotalDescuento,
			BigDecimal rolPagTotalLiquido, BigDecimal rolPagDcmTercero, BigDecimal rolPagDcmCuarto,
			BigDecimal rolPagDcmTerceroMensual, BigDecimal rolPagDcmCuartoMensual, BigDecimal rolPagPrestamoSindicato,
			BigDecimal rolPagMes, BigDecimal rolPagAnio, String rolPagPago, BigDecimal rolPagEstado,
			BigDecimal rolPagCoberturaSaludIess, BigDecimal prsId, Set<HistorialDescuento> historialDescuentos) {
		this.rolPagId = rolPagId;
		this.controlPago = controlPago;
		this.dtpsId = dtpsId;
		this.rolPagCodigoFuncionario = rolPagCodigoFuncionario;
		this.rolPagFacultad = rolPagFacultad;
		this.rolPagFuncion = rolPagFuncion;
		this.rolPagRmu = rolPagRmu;
		this.rolPagFondoReserva = rolPagFondoReserva;
		this.rolPagFondoReservaIess = rolPagFondoReservaIess;
		this.rolPagAporteIess = rolPagAporteIess;
		this.rolPagImpuestoRenta = rolPagImpuestoRenta;
		this.rolPagPrestamoIess = rolPagPrestamoIess;
		this.rolPagRetencionJudicial = rolPagRetencionJudicial;
		this.rolPagAnticipos = rolPagAnticipos;
		this.rolPagMultas = rolPagMultas;
		this.rolPagVarios = rolPagVarios;
		this.rolPagFondoMortuorio = rolPagFondoMortuorio;
		this.rolPagCesantiaAdicional = rolPagCesantiaAdicional;
		this.rolPagAsocEmpleados = rolPagAsocEmpleados;
		this.rolPagAsocProfesores = rolPagAsocProfesores;
		this.rolPagAsocFacultad = rolPagAsocFacultad;
		this.rolPagFomentoDeporte = rolPagFomentoDeporte;
		this.rolPagComisariato = rolPagComisariato;
		this.rolPagCoopAhoCredDocent = rolPagCoopAhoCredDocent;
		this.rolPagCesantia = rolPagCesantia;
		this.rolPagSeguros = rolPagSeguros;
		this.rolPagFondoJubIndexada = rolPagFondoJubIndexada;
		this.rolPagAlimentacion = rolPagAlimentacion;
		this.rolPagTransporte = rolPagTransporte;
		this.rolPagCargaFamiliar = rolPagCargaFamiliar;
		this.rolPagTotalIngreso = rolPagTotalIngreso;
		this.rolPagTotalDescuento = rolPagTotalDescuento;
		this.rolPagTotalLiquido = rolPagTotalLiquido;
		this.rolPagDcmTercero = rolPagDcmTercero;
		this.rolPagDcmCuarto = rolPagDcmCuarto;
		this.rolPagDcmTerceroMensual = rolPagDcmTerceroMensual;
		this.rolPagDcmCuartoMensual = rolPagDcmCuartoMensual;
		this.rolPagPrestamoSindicato = rolPagPrestamoSindicato;
		this.rolPagMes = rolPagMes;
		this.rolPagAnio = rolPagAnio;
		this.rolPagPago = rolPagPago;
		this.rolPagEstado = rolPagEstado;
		this.rolPagCoberturaSaludIess = rolPagCoberturaSaludIess;
		this.prsId = prsId;
		this.historialDescuentos = historialDescuentos;
	}

	@Id

	@Column(name = "ROL_PAG_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getRolPagId() {
		return this.rolPagId;
	}

	public void setRolPagId(int rolPagId) {
		this.rolPagId = rolPagId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CNT_PAG_ID_")
	public ControlPago getControlPago() {
		return this.controlPago;
	}

	public void setControlPago(ControlPago controlPago) {
		this.controlPago = controlPago;
	}

	@Column(name = "DTPS_ID", precision = 22, scale = 0)
	public BigDecimal getDtpsId() {
		return this.dtpsId;
	}

	public void setDtpsId(BigDecimal dtpsId) {
		this.dtpsId = dtpsId;
	}

	@Column(name = "ROL_PAG_CODIGO_FUNCIONARIO", length = 8)
	public String getRolPagCodigoFuncionario() {
		return this.rolPagCodigoFuncionario;
	}

	public void setRolPagCodigoFuncionario(String rolPagCodigoFuncionario) {
		this.rolPagCodigoFuncionario = rolPagCodigoFuncionario;
	}

	@Column(name = "ROL_PAG_FACULTAD", length = 128)
	public String getRolPagFacultad() {
		return this.rolPagFacultad;
	}

	public void setRolPagFacultad(String rolPagFacultad) {
		this.rolPagFacultad = rolPagFacultad;
	}

	@Column(name = "ROL_PAG_FUNCION", length = 64)
	public String getRolPagFuncion() {
		return this.rolPagFuncion;
	}

	public void setRolPagFuncion(String rolPagFuncion) {
		this.rolPagFuncion = rolPagFuncion;
	}

	@Column(name = "ROL_PAG_RMU", precision = 22, scale = 0)
	public BigDecimal getRolPagRmu() {
		return this.rolPagRmu;
	}

	public void setRolPagRmu(BigDecimal rolPagRmu) {
		this.rolPagRmu = rolPagRmu;
	}

	@Column(name = "ROL_PAG_FONDO_RESERVA", precision = 22, scale = 0)
	public BigDecimal getRolPagFondoReserva() {
		return this.rolPagFondoReserva;
	}

	public void setRolPagFondoReserva(BigDecimal rolPagFondoReserva) {
		this.rolPagFondoReserva = rolPagFondoReserva;
	}

	@Column(name = "ROL_PAG_FONDO_RESERVA_IESS", precision = 22, scale = 0)
	public BigDecimal getRolPagFondoReservaIess() {
		return this.rolPagFondoReservaIess;
	}

	public void setRolPagFondoReservaIess(BigDecimal rolPagFondoReservaIess) {
		this.rolPagFondoReservaIess = rolPagFondoReservaIess;
	}

	@Column(name = "ROL_PAG_APORTE_IESS", precision = 22, scale = 0)
	public BigDecimal getRolPagAporteIess() {
		return this.rolPagAporteIess;
	}

	public void setRolPagAporteIess(BigDecimal rolPagAporteIess) {
		this.rolPagAporteIess = rolPagAporteIess;
	}

	@Column(name = "ROL_PAG_IMPUESTO_RENTA", precision = 22, scale = 0)
	public BigDecimal getRolPagImpuestoRenta() {
		return this.rolPagImpuestoRenta;
	}

	public void setRolPagImpuestoRenta(BigDecimal rolPagImpuestoRenta) {
		this.rolPagImpuestoRenta = rolPagImpuestoRenta;
	}

	@Column(name = "ROL_PAG_PRESTAMO_IESS", precision = 22, scale = 0)
	public BigDecimal getRolPagPrestamoIess() {
		return this.rolPagPrestamoIess;
	}

	public void setRolPagPrestamoIess(BigDecimal rolPagPrestamoIess) {
		this.rolPagPrestamoIess = rolPagPrestamoIess;
	}

	@Column(name = "ROL_PAG_RETENCION_JUDICIAL", precision = 22, scale = 0)
	public BigDecimal getRolPagRetencionJudicial() {
		return this.rolPagRetencionJudicial;
	}

	public void setRolPagRetencionJudicial(BigDecimal rolPagRetencionJudicial) {
		this.rolPagRetencionJudicial = rolPagRetencionJudicial;
	}

	@Column(name = "ROL_PAG_ANTICIPOS", precision = 22, scale = 0)
	public BigDecimal getRolPagAnticipos() {
		return this.rolPagAnticipos;
	}

	public void setRolPagAnticipos(BigDecimal rolPagAnticipos) {
		this.rolPagAnticipos = rolPagAnticipos;
	}

	@Column(name = "ROL_PAG_MULTAS", precision = 22, scale = 0)
	public BigDecimal getRolPagMultas() {
		return this.rolPagMultas;
	}

	public void setRolPagMultas(BigDecimal rolPagMultas) {
		this.rolPagMultas = rolPagMultas;
	}

	@Column(name = "ROL_PAG_VARIOS", precision = 22, scale = 0)
	public BigDecimal getRolPagVarios() {
		return this.rolPagVarios;
	}

	public void setRolPagVarios(BigDecimal rolPagVarios) {
		this.rolPagVarios = rolPagVarios;
	}

	@Column(name = "ROL_PAG_FONDO_MORTUORIO", precision = 22, scale = 0)
	public BigDecimal getRolPagFondoMortuorio() {
		return this.rolPagFondoMortuorio;
	}

	public void setRolPagFondoMortuorio(BigDecimal rolPagFondoMortuorio) {
		this.rolPagFondoMortuorio = rolPagFondoMortuorio;
	}

	@Column(name = "ROL_PAG_CESANTIA_ADICIONAL", precision = 22, scale = 0)
	public BigDecimal getRolPagCesantiaAdicional() {
		return this.rolPagCesantiaAdicional;
	}

	public void setRolPagCesantiaAdicional(BigDecimal rolPagCesantiaAdicional) {
		this.rolPagCesantiaAdicional = rolPagCesantiaAdicional;
	}

	@Column(name = "ROL_PAG_ASOC_EMPLEADOS", precision = 22, scale = 0)
	public BigDecimal getRolPagAsocEmpleados() {
		return this.rolPagAsocEmpleados;
	}

	public void setRolPagAsocEmpleados(BigDecimal rolPagAsocEmpleados) {
		this.rolPagAsocEmpleados = rolPagAsocEmpleados;
	}

	@Column(name = "ROL_PAG_ASOC_PROFESORES", precision = 22, scale = 0)
	public BigDecimal getRolPagAsocProfesores() {
		return this.rolPagAsocProfesores;
	}

	public void setRolPagAsocProfesores(BigDecimal rolPagAsocProfesores) {
		this.rolPagAsocProfesores = rolPagAsocProfesores;
	}

	@Column(name = "ROL_PAG_ASOC_FACULTAD", precision = 22, scale = 0)
	public BigDecimal getRolPagAsocFacultad() {
		return this.rolPagAsocFacultad;
	}

	public void setRolPagAsocFacultad(BigDecimal rolPagAsocFacultad) {
		this.rolPagAsocFacultad = rolPagAsocFacultad;
	}

	@Column(name = "ROL_PAG_FOMENTO_DEPORTE", precision = 22, scale = 0)
	public BigDecimal getRolPagFomentoDeporte() {
		return this.rolPagFomentoDeporte;
	}

	public void setRolPagFomentoDeporte(BigDecimal rolPagFomentoDeporte) {
		this.rolPagFomentoDeporte = rolPagFomentoDeporte;
	}

	@Column(name = "ROL_PAG_COMISARIATO_", precision = 22, scale = 0)
	public BigDecimal getRolPagComisariato() {
		return this.rolPagComisariato;
	}

	public void setRolPagComisariato(BigDecimal rolPagComisariato) {
		this.rolPagComisariato = rolPagComisariato;
	}

	@Column(name = "ROL_PAG_COOP_AHO_CRED_DOCENT", precision = 22, scale = 0)
	public BigDecimal getRolPagCoopAhoCredDocent() {
		return this.rolPagCoopAhoCredDocent;
	}

	public void setRolPagCoopAhoCredDocent(BigDecimal rolPagCoopAhoCredDocent) {
		this.rolPagCoopAhoCredDocent = rolPagCoopAhoCredDocent;
	}

	@Column(name = "ROL_PAG_CESANTIA", precision = 22, scale = 0)
	public BigDecimal getRolPagCesantia() {
		return this.rolPagCesantia;
	}

	public void setRolPagCesantia(BigDecimal rolPagCesantia) {
		this.rolPagCesantia = rolPagCesantia;
	}

	@Column(name = "ROL_PAG_SEGUROS", precision = 22, scale = 0)
	public BigDecimal getRolPagSeguros() {
		return this.rolPagSeguros;
	}

	public void setRolPagSeguros(BigDecimal rolPagSeguros) {
		this.rolPagSeguros = rolPagSeguros;
	}

	@Column(name = "ROL_PAG_FONDO_JUB_INDEXADA", precision = 22, scale = 0)
	public BigDecimal getRolPagFondoJubIndexada() {
		return this.rolPagFondoJubIndexada;
	}

	public void setRolPagFondoJubIndexada(BigDecimal rolPagFondoJubIndexada) {
		this.rolPagFondoJubIndexada = rolPagFondoJubIndexada;
	}

	@Column(name = "ROL_PAG_ALIMENTACION", precision = 22, scale = 0)
	public BigDecimal getRolPagAlimentacion() {
		return this.rolPagAlimentacion;
	}

	public void setRolPagAlimentacion(BigDecimal rolPagAlimentacion) {
		this.rolPagAlimentacion = rolPagAlimentacion;
	}

	@Column(name = "ROL_PAG_TRANSPORTE", precision = 22, scale = 0)
	public BigDecimal getRolPagTransporte() {
		return this.rolPagTransporte;
	}

	public void setRolPagTransporte(BigDecimal rolPagTransporte) {
		this.rolPagTransporte = rolPagTransporte;
	}

	@Column(name = "ROL_PAG_CARGA_FAMILIAR", precision = 22, scale = 0)
	public BigDecimal getRolPagCargaFamiliar() {
		return this.rolPagCargaFamiliar;
	}

	public void setRolPagCargaFamiliar(BigDecimal rolPagCargaFamiliar) {
		this.rolPagCargaFamiliar = rolPagCargaFamiliar;
	}

	@Column(name = "ROL_PAG_TOTAL_INGRESO", precision = 22, scale = 0)
	public BigDecimal getRolPagTotalIngreso() {
		return this.rolPagTotalIngreso;
	}

	public void setRolPagTotalIngreso(BigDecimal rolPagTotalIngreso) {
		this.rolPagTotalIngreso = rolPagTotalIngreso;
	}

	@Column(name = "ROL_PAG_TOTAL_DESCUENTO", precision = 22, scale = 0)
	public BigDecimal getRolPagTotalDescuento() {
		return this.rolPagTotalDescuento;
	}

	public void setRolPagTotalDescuento(BigDecimal rolPagTotalDescuento) {
		this.rolPagTotalDescuento = rolPagTotalDescuento;
	}

	@Column(name = "ROL_PAG_TOTAL_LIQUIDO", precision = 22, scale = 0)
	public BigDecimal getRolPagTotalLiquido() {
		return this.rolPagTotalLiquido;
	}

	public void setRolPagTotalLiquido(BigDecimal rolPagTotalLiquido) {
		this.rolPagTotalLiquido = rolPagTotalLiquido;
	}

	@Column(name = "ROL_PAG_DCM_TERCERO", precision = 22, scale = 0)
	public BigDecimal getRolPagDcmTercero() {
		return this.rolPagDcmTercero;
	}

	public void setRolPagDcmTercero(BigDecimal rolPagDcmTercero) {
		this.rolPagDcmTercero = rolPagDcmTercero;
	}

	@Column(name = "ROL_PAG_DCM_CUARTO", precision = 22, scale = 0)
	public BigDecimal getRolPagDcmCuarto() {
		return this.rolPagDcmCuarto;
	}

	public void setRolPagDcmCuarto(BigDecimal rolPagDcmCuarto) {
		this.rolPagDcmCuarto = rolPagDcmCuarto;
	}

	@Column(name = "ROL_PAG_DCM_TERCERO_MENSUAL", precision = 22, scale = 0)
	public BigDecimal getRolPagDcmTerceroMensual() {
		return this.rolPagDcmTerceroMensual;
	}

	public void setRolPagDcmTerceroMensual(BigDecimal rolPagDcmTerceroMensual) {
		this.rolPagDcmTerceroMensual = rolPagDcmTerceroMensual;
	}

	@Column(name = "ROL_PAG_DCM_CUARTO_MENSUAL", precision = 22, scale = 0)
	public BigDecimal getRolPagDcmCuartoMensual() {
		return this.rolPagDcmCuartoMensual;
	}

	public void setRolPagDcmCuartoMensual(BigDecimal rolPagDcmCuartoMensual) {
		this.rolPagDcmCuartoMensual = rolPagDcmCuartoMensual;
	}

	@Column(name = "ROL_PAG_PRESTAMO_SINDICATO", precision = 22, scale = 0)
	public BigDecimal getRolPagPrestamoSindicato() {
		return this.rolPagPrestamoSindicato;
	}

	public void setRolPagPrestamoSindicato(BigDecimal rolPagPrestamoSindicato) {
		this.rolPagPrestamoSindicato = rolPagPrestamoSindicato;
	}

	@Column(name = "ROL_PAG_MES", precision = 22, scale = 0)
	public BigDecimal getRolPagMes() {
		return this.rolPagMes;
	}

	public void setRolPagMes(BigDecimal rolPagMes) {
		this.rolPagMes = rolPagMes;
	}

	@Column(name = "ROL_PAG_ANIO", precision = 22, scale = 0)
	public BigDecimal getRolPagAnio() {
		return this.rolPagAnio;
	}

	public void setRolPagAnio(BigDecimal rolPagAnio) {
		this.rolPagAnio = rolPagAnio;
	}

	@Column(name = "ROL_PAG_PAGO", length = 64)
	public String getRolPagPago() {
		return this.rolPagPago;
	}

	public void setRolPagPago(String rolPagPago) {
		this.rolPagPago = rolPagPago;
	}

	@Column(name = "ROL_PAG_ESTADO", precision = 22, scale = 0)
	public BigDecimal getRolPagEstado() {
		return this.rolPagEstado;
	}

	public void setRolPagEstado(BigDecimal rolPagEstado) {
		this.rolPagEstado = rolPagEstado;
	}

	@Column(name = "ROL_PAG_COBERTURA_SALUD_IESS", precision = 22, scale = 0)
	public BigDecimal getRolPagCoberturaSaludIess() {
		return this.rolPagCoberturaSaludIess;
	}

	public void setRolPagCoberturaSaludIess(BigDecimal rolPagCoberturaSaludIess) {
		this.rolPagCoberturaSaludIess = rolPagCoberturaSaludIess;
	}

	@Column(name = "PRS_ID", precision = 22, scale = 0)
	public BigDecimal getPrsId() {
		return this.prsId;
	}

	public void setPrsId(BigDecimal prsId) {
		this.prsId = prsId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rolPago")
	public Set<HistorialDescuento> getHistorialDescuentos() {
		return this.historialDescuentos;
	}

	public void setHistorialDescuentos(Set<HistorialDescuento> historialDescuentos) {
		this.historialDescuentos = historialDescuentos;
	}

}
