package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SaldoVacacion generated by hbm2java
 */
@Entity
@Table(name = "SALDO_VACACION", schema = "BDTALENTOHUMANO")
public class SaldoVacacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int slvcId;
	private DetallePuesto detallePuesto;
	private Integer slvcTotalDias;
	private Integer slvcDiasRegistrados;
	private Integer slvcDiasRestantes;
	private String slvcTotalHoras;
	private Integer slvcDiasAnticipados;
	private Integer slvcPeriodo;

	public SaldoVacacion() {
	}

	public SaldoVacacion(int slvcId) {
		this.slvcId = slvcId;
	}

	public SaldoVacacion(int slvcId, DetallePuesto detallePuesto, Integer slvcTotalDias,
			Integer slvcDiasRegistrados, Integer slvcDiasRestantes, String slvcTotalHoras,
			Integer slvcDiasAnticipados, Integer slvcPeriodo) {
		this.slvcId = slvcId;
		this.detallePuesto = detallePuesto;
		this.slvcTotalDias = slvcTotalDias;
		this.slvcDiasRegistrados = slvcDiasRegistrados;
		this.slvcDiasRestantes = slvcDiasRestantes;
		this.slvcTotalHoras = slvcTotalHoras;
		this.slvcDiasAnticipados = slvcDiasAnticipados;
		this.slvcPeriodo = slvcPeriodo;
	}

	@Id

	@Column(name = "SLVC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getSlvcId() {
		return this.slvcId;
	}

	public void setSlvcId(int slvcId) {
		this.slvcId = slvcId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTPS_ID")
	public DetallePuesto getDetallePuesto() {
		return this.detallePuesto;
	}

	public void setDetallePuesto(DetallePuesto detallePuesto) {
		this.detallePuesto = detallePuesto;
	}

	@Column(name = "SLVC_TOTAL_DIAS", precision = 22, scale = 0)
	public Integer getSlvcTotalDias() {
		return this.slvcTotalDias;
	}

	public void setSlvcTotalDias(Integer slvcTotalDias) {
		this.slvcTotalDias = slvcTotalDias;
	}

	@Column(name = "SLVC_DIAS_REGISTRADOS", precision = 22, scale = 0)
	public Integer getSlvcDiasRegistrados() {
		return this.slvcDiasRegistrados;
	}

	public void setSlvcDiasRegistrados(Integer slvcDiasRegistrados) {
		this.slvcDiasRegistrados = slvcDiasRegistrados;
	}

	@Column(name = "SLVC_DIAS_RESTANTES", precision = 22, scale = 0)
	public Integer getSlvcDiasRestantes() {
		return this.slvcDiasRestantes;
	}

	public void setSlvcDiasRestantes(Integer slvcDiasRestantes) {
		this.slvcDiasRestantes = slvcDiasRestantes;
	}

	
	@Column(name = "SLVC_TOTAL_HORAS", length = 5)
	public String getSlvcTotalHoras() {
		return this.slvcTotalHoras;
	}

	public void setSlvcTotalHoras(String slvcTotalHoras) {
		this.slvcTotalHoras = slvcTotalHoras;
	}

	@Column(name = "SLVC_DIAS_ANTICIPADOS", precision = 22, scale = 0)
	public Integer getSlvcDiasAnticipados() {
		return this.slvcDiasAnticipados;
	}

	public void setSlvcDiasAnticipados(Integer slvcDiasAnticipados) {
		this.slvcDiasAnticipados = slvcDiasAnticipados;
	}

	@Column(name = "SLVC__PERIODO", precision = 22, scale = 0)
	public Integer getSlvcPeriodo() {
		return this.slvcPeriodo;
	}

	public void setSlvcPeriodo(Integer slvcPeriodo) {
		this.slvcPeriodo = slvcPeriodo;
	}

	@Override
	public String toString() {
		return ""+slvcDiasRestantes+" Dias "+slvcTotalHoras +" HH:MM";
	}

}
