package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TipoLicencia generated by hbm2java
 */
@Entity
@Table(name = "TIPO_LICENCIA", schema = "BDTALENTOHUMANO")
public class TipoLicencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int tplcId;
	private String tplcNombre;
	private String tplcDescripcion;
	private BigDecimal tplcEstado;
	private Set<LicenciaYPermiso> licenciaYPermisos = new HashSet<LicenciaYPermiso>(0);

	public TipoLicencia() {
	}

	public TipoLicencia(int tplcId) {
		this.tplcId = tplcId;
	}

	public TipoLicencia(int tplcId, String tplcNombre, String tplcDescripcion, BigDecimal tplcEstado,
			Set<LicenciaYPermiso> licenciaYPermisos) {
		this.tplcId = tplcId;
		this.tplcNombre = tplcNombre;
		this.tplcDescripcion = tplcDescripcion;
		this.tplcEstado = tplcEstado;
		this.licenciaYPermisos = licenciaYPermisos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TipoLicIdGenerator")
    @SequenceGenerator(name = "TipoLicIdGenerator", initialValue = 1, allocationSize = 1, sequenceName = "S_TIPO_LICENCIA")
	@Column(name = "TPLC_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int  getTplcId() {
		return this.tplcId;
	}

	public void setTplcId(int tplcId) {
		this.tplcId = tplcId;
	}

	@Column(name = "TPLC_NOMBRE", length = 256)
	public String getTplcNombre() {
		return this.tplcNombre;
	}

	public void setTplcNombre(String tplcNombre) {
		this.tplcNombre = tplcNombre;
	}

	@Column(name = "TPLC_DESCRIPCION", length = 512)
	public String getTplcDescripcion() {
		return this.tplcDescripcion;
	}

	public void setTplcDescripcion(String tplcDescripcion) {
		this.tplcDescripcion = tplcDescripcion;
	}

	@Column(name = "TPLC_ESTADO", precision = 22, scale = 0)
	public BigDecimal getTplcEstado() {
		return this.tplcEstado;
	}

	public void setTplcEstado(BigDecimal tplcEstado) {
		this.tplcEstado = tplcEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoLicencia")
	public Set<LicenciaYPermiso> getLicenciaYPermisos() {
		return this.licenciaYPermisos;
	}

	public void setLicenciaYPermisos(Set<LicenciaYPermiso> licenciaYPermisos) {
		this.licenciaYPermisos = licenciaYPermisos;
	}

}
