package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAccion generated by hbm2java
 */
@Entity
@Table(name = "TIPO_ACCION", schema = "BDTALENTOHUMANO")
public class TipoAccion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int tpacId;
	private String tpacDescripcion;
	private Set<AccionPersonal> accionPersonals = new HashSet<AccionPersonal>(0);

	public TipoAccion() {
	}

	public TipoAccion(int tpacId) {
		this.tpacId = tpacId;
	}

	public TipoAccion(int tpacId, String tpacDescripcion, Set<AccionPersonal> accionPersonals) {
		this.tpacId = tpacId;
		this.tpacDescripcion = tpacDescripcion;
		this.accionPersonals = accionPersonals;
	}

	@Id

	@Column(name = "TPAC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTpacId() {
		return this.tpacId;
	}

	public void setTpacId(int tpacId) {
		this.tpacId = tpacId;
	}

	@Column(name = "TPAC_DESCRIPCION", length = 256)
	public String getTpacDescripcion() {
		return this.tpacDescripcion;
	}

	public void setTpacDescripcion(String tpacDescripcion) {
		this.tpacDescripcion = tpacDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAccion")
	public Set<AccionPersonal> getAccionPersonals() {
		return this.accionPersonals;
	}

	public void setAccionPersonals(Set<AccionPersonal> accionPersonals) {
		this.accionPersonals = accionPersonals;
	}

}
