package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoEmpleado generated by hbm2java
 */
@Entity
@Table(name = "TIPO_EMPLEADO", schema = "BDTALENTOHUMANO")
public class TipoEmpleado implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int tpemId;
	private String tpemDescripcion;
	private BigDecimal tpemEstado;
	private Set<FichaEmpleado> fichaEmpleados = new HashSet<FichaEmpleado>(0);

	public TipoEmpleado() {
	}

	public TipoEmpleado(int tpemId) {
		this.tpemId = tpemId;
	}

	public TipoEmpleado(int tpemId, String tpemDescripcion, BigDecimal tpemEstado, Set<FichaEmpleado> fichaEmpleados) {
		this.tpemId = tpemId;
		this.tpemDescripcion = tpemDescripcion;
		this.tpemEstado = tpemEstado;
		this.fichaEmpleados = fichaEmpleados;
	}

	@Id

	@Column(name = "TPEM_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTpemId() {
		return this.tpemId;
	}

	public void setTpemId(int tpemId) {
		this.tpemId = tpemId;
	}

	@Column(name = "TPEM_DESCRIPCION", length = 512)
	public String getTpemDescripcion() {
		return this.tpemDescripcion;
	}

	public void setTpemDescripcion(String tpemDescripcion) {
		this.tpemDescripcion = tpemDescripcion;
	}

	@Column(name = "TPEM_ESTADO", precision = 22, scale = 0)
	public BigDecimal getTpemEstado() {
		return this.tpemEstado;
	}

	public void setTpemEstado(BigDecimal tpemEstado) {
		this.tpemEstado = tpemEstado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoEmpleado")
	public Set<FichaEmpleado> getFichaEmpleados() {
		return this.fichaEmpleados;
	}

	public void setFichaEmpleados(Set<FichaEmpleado> fichaEmpleados) {
		this.fichaEmpleados = fichaEmpleados;
	}

}
