package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * TipoLicencia generated by hbm2java
 */
@Entity
@Table(name = "TIPO_LICENCIA", schema = "BDTALENTOHUMANO")
public class TipoLicencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int tplcId;
	private String tplcNombre;
	private String tplcDescripcion;
	private int tplcEstado;
	private int tplcPadre;
	private int tplcMaxDias;
	private int tplcMinDias;
	private Set<Licencia> licenciaYPermisos = new HashSet<Licencia>(0);

	public TipoLicencia() {
	}

	public TipoLicencia(int tplcId) {
		this.tplcId = tplcId;
	}

	public TipoLicencia(int tplcId, String tplcNombre, String tplcDescripcion, int tplcEstado, int tplcPadre, int tplcMaxDias, int tplcMinDias,
			Set<Licencia> licenciaYPermisos) {
		this.tplcId = tplcId;
		this.tplcNombre = tplcNombre;
		this.tplcDescripcion = tplcDescripcion;
		this.tplcEstado = tplcEstado;
		this.tplcPadre = tplcPadre;
		this.tplcMaxDias = tplcMaxDias;
		this.tplcMinDias = tplcMinDias;
		this.licenciaYPermisos = licenciaYPermisos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TipoLicIdGenerator")
    @SequenceGenerator(name = "TipoLicIdGenerator", initialValue = 1, allocationSize = 1, sequenceName = "S_TIPO_LICENCIA")
	@Column(name = "TPLC_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public int  getTplcId() {
		return this.tplcId;
	}

	public void setTplcId(int tplcId) {
		this.tplcId = tplcId;
	}

	@Column(name = "TPLC_NOMBRE", length = 256)
	public String getTplcNombre() {
		return this.tplcNombre;
	}

	public void setTplcNombre(String tplcNombre) {
		this.tplcNombre = tplcNombre;
	}

	@Column(name = "TPLC_DESCRIPCION", length = 512)
	public String getTplcDescripcion() {
		return this.tplcDescripcion;
	}

	public void setTplcDescripcion(String tplcDescripcion) {
		this.tplcDescripcion = tplcDescripcion;
	}

	@Column(name = "TPLC_ESTADO", precision = 22, scale = 0)
	public int getTplcEstado() {
		return this.tplcEstado;
	}

	public void setTplcEstado(int tplcEstado) {
		this.tplcEstado = tplcEstado;
	}
	
	
	@Column(name = "TPLC_PADRE", precision = 22, scale = 0)
	public int getTplcPadre() {
		return tplcPadre;
	}

	public void setTplcPadre(int tplcPadre) {
		this.tplcPadre = tplcPadre;
	}
	@Column(name = "TPLC_MAX_DIAS", precision = 22, scale = 0)
	public int getTplcMaxDias() {
		return tplcMaxDias;
	}

	public void setTplcMaxDias(int tplcMaxDias) {
		this.tplcMaxDias = tplcMaxDias;
	}
	@Column(name = "TPLC_MIN_DIAS", precision = 22, scale = 0)
	public int getTplcMinDias() {
		return tplcMinDias;
	}

	public void setTplcMinDias(int tplcMinDias) {
		this.tplcMinDias = tplcMinDias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoLicencia")
	public Set<Licencia> getLicenciaYPermisos() {
		return this.licenciaYPermisos;
	}

	public void setLicenciaYPermisos(Set<Licencia> licenciaYPermisos) {
		this.licenciaYPermisos = licenciaYPermisos;
	}

}
