package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoContrato generated by hbm2java
 */
@Entity
@Table(name = "TIPO_CONTRATO", schema = "BDTALENTOHUMANO")
public class TipoContrato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int tpcnId;
	private String tpcnDescripcion;
	private Set<Contrato> contratos = new HashSet<Contrato>(0);

	public TipoContrato() {
	}

	public TipoContrato(int tpcnId) {
		this.tpcnId = tpcnId;
	}

	public TipoContrato(int tpcnId, String tpcnDescripcion, Set<Contrato> contratos) {
		this.tpcnId = tpcnId;
		this.tpcnDescripcion = tpcnDescripcion;
		this.contratos = contratos;
	}

	@Id

	@Column(name = "TPCN_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTpcnId() {
		return this.tpcnId;
	}

	public void setTpcnId(int tpcnId) {
		this.tpcnId = tpcnId;
	}

	@Column(name = "TPCN_DESCRIPCION", length = 256)
	public String getTpcnDescripcion() {
		return this.tpcnDescripcion;
	}

	public void setTpcnDescripcion(String tpcnDescripcion) {
		this.tpcnDescripcion = tpcnDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoContrato")
	public Set<Contrato> getContratos() {
		return this.contratos;
	}

	public void setContratos(Set<Contrato> contratos) {
		this.contratos = contratos;
	}

}
