package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Time;
import java.sql.Timestamp;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tramite generated by hbm2java
 */
@Entity
@Table(name = "TRAMITE", schema = "BDTALENTOHUMANO")
public class Tramite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int trmId;
	private Puesto puesto;
	private String trmObservacion;
	private BigDecimal trmEstado;
	private Timestamp trmFecha;
	private String trmUsuario;
	private String trmArchivo;
	private Set<Candidato> candidatos = new HashSet<Candidato>(0);

	public Tramite() {
	}

	public Tramite(int trmId) {
		this.trmId = trmId;
	}

	public Tramite(int trmId, Puesto puesto, String trmObservacion, BigDecimal trmEstado, Timestamp trmFecha,
			String trmUsuario, String trmArchivo, Set<Candidato> candidatos) {
		this.trmId = trmId;
		this.puesto = puesto;
		this.trmObservacion = trmObservacion;
		this.trmEstado = trmEstado;
		this.trmFecha = trmFecha;
		this.trmUsuario = trmUsuario;
		this.trmArchivo = trmArchivo;
		this.candidatos = candidatos;
	}

	@Id

	@Column(name = "TRM_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTrmId() {
		return this.trmId;
	}

	public void setTrmId(int trmId) {
		this.trmId = trmId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PST_ID")
	public Puesto getPuesto() {
		return this.puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}

	@Column(name = "TRM_OBSERVACION", length = 512)
	public String getTrmObservacion() {
		return this.trmObservacion;
	}

	public void setTrmObservacion(String trmObservacion) {
		this.trmObservacion = trmObservacion;
	}

	@Column(name = "TRM_ESTADO", precision = 22, scale = 0)
	public BigDecimal getTrmEstado() {
		return this.trmEstado;
	}

	public void setTrmEstado(BigDecimal trmEstado) {
		this.trmEstado = trmEstado;
	}

	@Column(name = "TRM_FECHA")
	public Timestamp getTrmFecha() {
		return this.trmFecha;
	}

	public void setTrmFecha(Timestamp trmFecha) {
		this.trmFecha = trmFecha;
	}

	@Column(name = "TRM_USUARIO", length = 256)
	public String getTrmUsuario() {
		return this.trmUsuario;
	}

	public void setTrmUsuario(String trmUsuario) {
		this.trmUsuario = trmUsuario;
	}

	@Column(name = "TRM_ARCHIVO", length = 512)
	public String getTrmArchivo() {
		return this.trmArchivo;
	}

	public void setTrmArchivo(String trmArchivo) {
		this.trmArchivo = trmArchivo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tramite")
	public Set<Candidato> getCandidatos() {
		return this.candidatos;
	}

	public void setCandidatos(Set<Candidato> candidatos) {
		this.candidatos = candidatos;
	}

}
