package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "USUARIO", schema = "BDTALENTOHUMANO")
public class Usuario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int usrId;
	private Persona persona;
	private String usrIdentificacion;
	private String usrNick;
	private String usrPassword;
	private Serializable usrFechaCreacion;
	private Date usrFechaCaducidad;
	private Date usrFechaCadPass;
	private BigDecimal usrEstado;
	private BigDecimal usrEstSesion;
	private BigDecimal usrActiveDirectory;
	private Set<UsuarioRol> usuarioRols = new HashSet<UsuarioRol>(0);
	private Set<ControlPago> controlPagos = new HashSet<ControlPago>(0);

	public Usuario() {
	}

	public Usuario(int usrId) {
		this.usrId = usrId;
	}

	public Usuario(int usrId, Persona persona, String usrIdentificacion, String usrNick, String usrPassword,
			Serializable usrFechaCreacion, Date usrFechaCaducidad, Date usrFechaCadPass, BigDecimal usrEstado,
			BigDecimal usrEstSesion, BigDecimal usrActiveDirectory, Set<UsuarioRol> usuarioRols,
			Set<ControlPago> controlPagos) {
		this.usrId = usrId;
		this.persona = persona;
		this.usrIdentificacion = usrIdentificacion;
		this.usrNick = usrNick;
		this.usrPassword = usrPassword;
		this.usrFechaCreacion = usrFechaCreacion;
		this.usrFechaCaducidad = usrFechaCaducidad;
		this.usrFechaCadPass = usrFechaCadPass;
		this.usrEstado = usrEstado;
		this.usrEstSesion = usrEstSesion;
		this.usrActiveDirectory = usrActiveDirectory;
		this.usuarioRols = usuarioRols;
		this.controlPagos = controlPagos;
	}

	@Id

	@Column(name = "USR_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getUsrId() {
		return this.usrId;
	}

	public void setUsrId(int usrId) {
		this.usrId = usrId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PRS_ID")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "USR_IDENTIFICACION", length = 13)
	public String getUsrIdentificacion() {
		return this.usrIdentificacion;
	}

	public void setUsrIdentificacion(String usrIdentificacion) {
		this.usrIdentificacion = usrIdentificacion;
	}

	@Column(name = "USR_NICK", length = 20)
	public String getUsrNick() {
		return this.usrNick;
	}

	public void setUsrNick(String usrNick) {
		this.usrNick = usrNick;
	}

	@Column(name = "USR_PASSWORD", length = 64)
	public String getUsrPassword() {
		return this.usrPassword;
	}

	public void setUsrPassword(String usrPassword) {
		this.usrPassword = usrPassword;
	}

	@Column(name = "USR_FECHA_CREACION")
	public Serializable getUsrFechaCreacion() {
		return this.usrFechaCreacion;
	}

	public void setUsrFechaCreacion(Serializable usrFechaCreacion) {
		this.usrFechaCreacion = usrFechaCreacion;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "USR_FECHA_CADUCIDAD", length = 7)
	public Date getUsrFechaCaducidad() {
		return this.usrFechaCaducidad;
	}

	public void setUsrFechaCaducidad(Date usrFechaCaducidad) {
		this.usrFechaCaducidad = usrFechaCaducidad;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "USR_FECHA_CAD_PASS", length = 7)
	public Date getUsrFechaCadPass() {
		return this.usrFechaCadPass;
	}

	public void setUsrFechaCadPass(Date usrFechaCadPass) {
		this.usrFechaCadPass = usrFechaCadPass;
	}

	@Column(name = "USR_ESTADO", precision = 22, scale = 0)
	public BigDecimal getUsrEstado() {
		return this.usrEstado;
	}

	public void setUsrEstado(BigDecimal usrEstado) {
		this.usrEstado = usrEstado;
	}

	@Column(name = "USR_EST_SESION", precision = 22, scale = 0)
	public BigDecimal getUsrEstSesion() {
		return this.usrEstSesion;
	}

	public void setUsrEstSesion(BigDecimal usrEstSesion) {
		this.usrEstSesion = usrEstSesion;
	}

	@Column(name = "USR_ACTIVE_DIRECTORY", precision = 22, scale = 0)
	public BigDecimal getUsrActiveDirectory() {
		return this.usrActiveDirectory;
	}

	public void setUsrActiveDirectory(BigDecimal usrActiveDirectory) {
		this.usrActiveDirectory = usrActiveDirectory;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioRol> getUsuarioRols() {
		return this.usuarioRols;
	}

	public void setUsuarioRols(Set<UsuarioRol> usuarioRols) {
		this.usuarioRols = usuarioRols;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<ControlPago> getControlPagos() {
		return this.controlPagos;
	}

	public void setControlPagos(Set<ControlPago> controlPagos) {
		this.controlPagos = controlPagos;
	}

}
