package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioRol generated by hbm2java
 */
@Entity
@Table(name = "USUARIO_ROL", schema = "BDTALENTOHUMANO")
public class UsuarioRol implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int usroId;
	private Rol rol;
	private Usuario usuario;
	private BigDecimal usroEstado;

	public UsuarioRol() {
	}

	public UsuarioRol(int usroId) {
		this.usroId = usroId;
	}

	public UsuarioRol(int usroId, Rol rol, Usuario usuario, BigDecimal usroEstado) {
		this.usroId = usroId;
		this.rol = rol;
		this.usuario = usuario;
		this.usroEstado = usroEstado;
	}

	@Id

	@Column(name = "USRO_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getUsroId() {
		return this.usroId;
	}

	public void setUsroId(int usroId) {
		this.usroId = usroId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROL_ID")
	public Rol getRol() {
		return this.rol;
	}

	public void setRol(Rol rol) {
		this.rol = rol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USR_ID")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "USRO_ESTADO", precision = 22, scale = 0)
	public BigDecimal getUsroEstado() {
		return this.usroEstado;
	}

	public void setUsroEstado(BigDecimal usroEstado) {
		this.usroEstado = usroEstado;
	}

}
