package ec.edu.uce.controlAsistencia.jpa.entidades;
// Generated 07-mar-2018 22:35:26 by Hibernate Tools 4.3.5.Final


import java.sql.Timestamp;
import java.util.Date;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vacacion generated by hbm2java
 */
@Entity
@Table(name = "VACACION", schema = "BDTALENTOHUMANO")
public class Vacacion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int vccId;
	private DetallePuesto detallePuesto;
	private int vccNumAutorizacion;
	private Timestamp vccFechaEmision;
	private int vccNumDias;
	private Date vccFechaInicio;
	private Date vccFechaFin;
	private String vccObservacion;
	private String vccCopia;
	private int vccEstado;
	private String vccObservacionEstado;

	public Vacacion() {
	}

	public Vacacion(int vccId) {
		this.vccId = vccId;
	}

	public Vacacion(int vccId, DetallePuesto detallePuesto, int vccNumAutorizacion, Timestamp vccFechaEmision,
			int vccNumDias, Date vccFechaInicio, Date vccFechaFin, String vccObservacion, String vccCopia,
			int vccEstado, String vccObservacionEstado) {
		this.vccId = vccId;
		this.detallePuesto = detallePuesto;
		this.vccNumAutorizacion = vccNumAutorizacion;
		this.vccFechaEmision = vccFechaEmision;
		this.vccNumDias = vccNumDias;
		this.vccFechaInicio = vccFechaInicio;
		this.vccFechaFin = vccFechaFin;
		this.vccObservacion = vccObservacion;
		this.vccCopia = vccCopia;
		this.vccEstado = vccEstado;
		this.vccObservacionEstado = vccObservacionEstado;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "AccountIdGenerator")
    @SequenceGenerator(name = "AccountIdGenerator", initialValue = 1, allocationSize = 1, sequenceName = "S_VACACION")
	@Column(name = "VCC_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getVccId() {
		return this.vccId;
	} 

	public void setVccId(int vccId) {
		this.vccId = vccId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DTPS_ID")
	public DetallePuesto getDetallePuesto() {
		return this.detallePuesto;
	}

	public void setDetallePuesto(DetallePuesto detallePuesto) {
		this.detallePuesto = detallePuesto;
	}

	@Column(name = "VCC_NUM_AUTORIZACION", precision = 22, scale = 0)
	public int getVccNumAutorizacion() {
		return this.vccNumAutorizacion;
	}

	public void setVccNumAutorizacion(int vccNumAutorizacion) {
		this.vccNumAutorizacion = vccNumAutorizacion;
	}

	@Column(name = "VCC_FECHA_EMISION")
	public Timestamp getVccFechaEmision() {
		return this.vccFechaEmision;
	}

	public void setVccFechaEmision(Timestamp vccFechaEmision) {
		this.vccFechaEmision = vccFechaEmision;
	}

	@Column(name = "VCC_NUM_DIAS", precision = 22, scale = 0)
	public int getVccNumDias() {
		return this.vccNumDias;
	}

	public void setVccNumDias(int  vccNumDias) {
		this.vccNumDias = vccNumDias;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VCC_FECHA_INICIO", length = 7)
	public Date getVccFechaInicio() {
		return this.vccFechaInicio;                     
	}

	public void setVccFechaInicio(Date vccFechaInicio) {
		this.vccFechaInicio = vccFechaInicio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "VCC_FECHA_FIN", length = 7)
	public Date getVccFechaFin() {
		return this.vccFechaFin;
	}

	public void setVccFechaFin(Date vccFechaFin) {
		this.vccFechaFin = vccFechaFin;
	}

	@Column(name = "VCC_OBSERVACION", length = 512)
	public String getVccObservacion() {
		return this.vccObservacion;
	}

	public void setVccObservacion(String vccObservacion) {
		this.vccObservacion = vccObservacion;
	}

	@Column(name = "VCC_COPIA", length = 512)
	public String getVccCopia() {
		return this.vccCopia;
	}

	public void setVccCopia(String vccCopia) {
		this.vccCopia = vccCopia;
	}

	@Column(name = "VCC_ESTADO", precision = 22, scale = 0)
	public int getVccEstado() {
		return this.vccEstado;
	}

	public void setVccEstado(int vccEstado) {
		this.vccEstado = vccEstado;
	}

	@Column(name = "VCC_OBSERVACION_ESTADO", length = 512)
	public String getVccObservacionEstado() {
		return this.vccObservacionEstado;
	}

	public void setVccObservacionEstado(String vccObservacionEstado) {
		this.vccObservacionEstado = vccObservacionEstado;
	}

}
